### ISSUE TITLE
Create Colouring Britain repository & regional academic hub central resource & set-up UK building footprint framework

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#10]
@mdsimpson42 @matkoniecz @fallipalaiologou 

- [ ] Rename Colouring London Colouring Britain (if this is the most sensible way to create the national repo).
- [ ] Load in Microsoft/Bing footprints
- [ ] Create OS MasterMap toggle option for Colouring London and Colouring Loughborough and set OSMM as default for both if possible
- [ ] Load in INSPIRE data as layer for London and Loughborough initially add to toggle option
- [ ] Load in OS OpenMap Local add to toggle option
- [ ] Create facility to highlight errors or correct Microsoft/Bing footprints as these will be used as data filing cabinets  for all areas except London Loughborough and possibly Exeter

**Comment by mdsimpson42** [comment]
How high priority is this? Is this something that you would like done before I go away or can it wait until I get back? (I'm going to have to manage my time very carefully this week)

**Comment by mdsimpson42** [comment]
I suspect loading in the new data sources isn't going to be a simple job.
We may need to discuss whether its better to rename Colouring London or create a separate one...
