### ISSUE TITLE
Planning section Outstanding technical ready for Launch 

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-london#1002]
- [x] "Heritage assets and building protection" -> add option to switch to empty map style
- [x] decide on styling ( `<TextSymbolizer size="16" fill="#f55" face-name="DejaVu Serif Book" halo-radius="0.1" wrap-width="20">` ?)
- [x] i have just been through it again actually  think we need to move the 2 inactive sections to the bottom as they are quite confusing and there is so much info to take in. Could you just copy and paste these today to the bottom of the edit panel list with a new main title saying 'Forthcoming data (sections to be activated)' and add the subtitle below for each the 2 inactive sections  (we can remove word' inactive' currently  in brackets at end of these subtitles)- many thanks
- [x] Heritage assets and building protection - two buttons that should be aligned (if easy)
- [x] In Past applications not sure what this means  ' No live planning data for this date range, but this building has associated planning data now shown here'. should it just say 'No streamed planning data available'?
   - [x] fix now/not typo
   - [x] split it in two variants "Only past application data is currently available for this site" "Only current application data is currently available for this site" - definitely needed for current applications
- [x] key name in dropdown change in legend on pink button use
- [x] borough names
   - [x] add test polygon into database and render its name as a test for the next step
   - [x] load borough data into database, rather than storing as geojson (necessary for the label display)
   - [x] render borough boundaries from database

- [x] add on landing page the menu with 12 squares - (can be nonfunctional) - https://cl-staging.uksouth.cloudapp.azure.com/
- [x] better border styling for CA
  - [x] replaces: dynamic change of border style for conservation areas - is possible with current setup or is it requiring Mapnik?
- [x] add this extra button for CA in planning
   - [x] replaces this: Make conservation areas come up at same time as pink button is clicked (?)
- [x]  Minor edit to text under Current Planning Applications'To see planning applications visualised for different periods click on the map key dropdown. To comment on an application follow the application link if provided, or visit the relevant local authority's planning page'
- [x] can we copy code for  pink button - here for land parcels saying 'click to see  land parcels outlines and to add ownership-type data'  - otherwise not consistent and means land parcels aren't linked in - thanks
- [x] Make conservation areas falling underneath other protected asset data
- [x] swap green and blue boxes in planning section
- [x] #1000
- [x] #1005
- [x] #998
- [x] pink button on future section to switch map style
- [x] pink button in Building protection section
- [x] pink buttons in Community section
- [x] we need to link the map layers to the automatic opening of the last two categories- i.e so when user opens the 'protected buildings' category in the edit panel, the protected/ designated building layer comes up, likewise for land ownership- land parcels come up. Do you need pink buttons for this? In the long run it would be ideal if when you opened the category the map appeared maybe we could add for future work?
- [x] tweaking of text in boxes
- [x] fix temporary auth provider misuse
- [x] unify css files for layer buttons
- [x] the same size for layer buttons
- [x] enable night mode for them
- [x] To comment on applications follow the application link or find application in local authority's portal and comment there
- [x]  In Planning Zones change the text  in blue box to say ''To view planning zone data for London click the pink buttons. You may need to zoom out'
- [x] -make show/hide layers button more distinctive from layer buttons
- [x] is select a building always visible for you when you click on planning section and  turquoise highlight always visible when opening the planning application section? Why does  it not reset on mine? 
- [x] Under zones not sure if key should disappear ( and be replaced by planning zone key) as i zoom out  as otherwise i'm looking at planning zones but key could say 'expected planning applications' which is v confusing  
- [x] I think we need to underline 'zoom out' under the planning zone section as otherwise they won't understand what they are seeing
- [x] Should we shut one category automatically when another is opened as gets quite chaotic - discussed and no
- [x] - can we make everything in all disclaimer boxes in italics.
- [x]  Under 'Planning zones', and 'protection' can you put any information relating to the GLA source of data in italicised format too - so we have blue for instructions, green for live streaming, yellow for unactivated, pale grey/italic for info on GLA source and disclaimer and pink buttons to bring up appropriate maps
- [x] Under Planning zones hide the YES/NO for the moment and remove the 'Information will be generated automatically in future) .  I think this is probably unnecessary and confusing for the moment
- [x] Under Current Planning Applications, crowdsourced data Remove the 2 yellow unactivated buttons and instead on the main category titles add (to be activated) ' in brackets having this in brackets - this because it will be annoying for some people to open categories that don't work while for others it will be interesting to see what is planned. Do the same for the Ownership category
- [x] Rename 'Building protection'- 'Heritage assets and building protection'
- [x] In this section the blue button should say  ' Please help us produce the most accurate map possible of London's historic buildings, by adding data where missing and verifying official data where accurately mapped.
- [x] Change text on pink button to say' 'Click here to see the protected buildings map' 
- [x] For Past planning applications blue box should now read
' This section provides data on past applications where available from the GLA, including those with no decision in over a year'  
- [x]  In 'Future applications move the pink box to below the blue box and change the text to say ' Click here to view possible locations of future applications'
- [x]  In 'Future applications add the word 'also' to the sentence 'Click and colour buildings here if you think that there will be a future planning application. To add your opinion on how well this building works for the community, please **also** visit the Community section'.
- [x] Can we change the blue colour  for 'submitted' applications as the architect I was consulting yesterday said she found similarity v confusing- maybe not blue at all? (purple)
- [x] readd "To see planning applications visualised for different periods click on the map key dropdown." in "Current/active applications (official data)" section
- [x] fix credit https://github.com/colouring-cities/colouring-london/issues/1002#issuecomment-1356841566

# Deployment

- [ ] merge and deploy on the main site additional data layers
- [ ] monitor automatic streaming after merge
- [ ] merge and deploy on the main site planning data 

# Phase 2

- [ ] bluesky: https://cl-staging.uksouth.cloudapp.azure.com/view/planning/2481763 - link with building id should center on building when opened (this enables better sharing of interesting buildings, including ones with planning application important to someone) - `const [position, setPosition] = useState(initialMapViewport.position);` would need to detect current URL (`map.tsx` has `selectedBuildingId` info!) and load position of building (how?)
@matkoniecz have added these - trying out with family and still quite hard to navigate.
  - [ ] being able to zoom back/recentre once you've zoomed out is important - discussed and underway
  - [ ] is there an easier way to go to ID link and back again- should it open in same page- discussed and underway
- [ ] technical, invisible to users: extract pink inline button into a react component
- [ ] For Past planning applications we can now hide the disclaimer in this section
- [ ] also for land parcels can you unhide the dropdown if possible  (so people can still click arrow and see ownership types classes if possible even if not activated
- [ ] Check on mobile devices

**Comment by matkoniecz** [comment]
@matkoniecz ping

**Comment by polly64** [comment]
@matkoniecz Hi Matuesz could you possibly update the feature we talked about this morning - the one first on the list i can't start video without it. thanks

**Comment by matkoniecz** [comment]
@polly64 Changed!

**Comment by polly64** [comment]
@matkoniecz   for conservation area credit should say Ian Hall not Leo Hall

**Comment by matkoniecz** [comment]
@polly64 This also should be fixed

**Comment by polly64** [comment]
@matkoniecz thanks

**Comment by polly64** [comment]
I just noticed that Ian Hall asks for dataset to be titles as 'English Conservation Area dataset 2020' could you add?

**Comment by polly64** [comment]
@matkoniecz hi Mateusz let me know how you're progressing

**Comment by matkoniecz** [comment]
@polly64 

Just fixed " key name in dropdown change in legend on pink button use" - I am deploying it on staging together with what Mike did for this welcome page.

**Comment by matkoniecz** [comment]
@polly64 Both should be there now :)

**Comment by matkoniecz** [comment]
pinged in https://github.com/colouring-cities/colouring-london/pull/898#issuecomment-1361765104

**Comment by polly64** [comment]
@matkoniecz thanks

**Comment by polly64** [comment]
@matkoniecz In the current planning section its says 'No live planning data for this date range, but this building has associated planning data not shown here'. think we were going to change this one

**Comment by matkoniecz** [comment]
@polly64 Fixed now!

**Comment by polly64** [comment]
@matkoniecz thanks!

**Comment by polly64** [comment]
@matkoniecz I have v slow internet here but could u double check the heritage asset pink button is working?

**Comment by matkoniecz** [comment]
it is :)

**Comment by matkoniecz** [comment]
bulk of TODOs is done, I will split remaining subtasks into new issues
