### ISSUE TITLE
Planning section deployment

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-london#1009]
- [x] process reviews if any
- [x] merge PR https://github.com/colouring-cities/colouring-london/pull/898 (can be done by @mdsimpson42 or @tomalrussell )
- [x] deploy on the main site additional data layers
- [ ] monitor automatic streaming after merge
- [x] merge and deploy on the main site planning data

**Comment by matkoniecz** [comment]
was part of #1002

**Comment by polly64** [comment]
@matkoniecz not seeing borough boundaries?

**Comment by matkoniecz** [comment]
I will do this once I got back from trip (on 3rd January)

**Comment by polly64** [comment]
many thanks

**Comment by matkoniecz** [comment]
@polly64 Do you want to keep size from the second image on the third one?

Or do you wish to adjust text size at some other zoom level?

![screen01](https://user-images.githubusercontent.com/899988/210360731-d111874c-d7a3-4424-a2d8-fb06e38203df.png)
![screen02](https://user-images.githubusercontent.com/899988/210360728-7583e011-d351-420d-ba76-13e084126454.png)
![screen03](https://user-images.githubusercontent.com/899988/210360722-c5091579-ad06-4dae-ba2a-f35052386d21.png)

**Comment by matkoniecz** [comment]
@polly64 

>  on Location section change 'Building name information (link)' to 'Building Name (Information link)

Do you mean that field?

![screen04](https://user-images.githubusercontent.com/899988/210373522-8c3abe7b-101e-4ba2-99cd-2ce3811bfb19.png)

**Comment by matkoniecz** [comment]
@polly64 

>  on 'Search feature' allow you to search area without double clicking the postcode image attached

So you would want to move map to the first postcode on the list, if matching, on clicking "search" button?

**Comment by matkoniecz** [comment]
@polly64 

> do you understand why there s a dropdown?

probably to help in cases where matches are not exact? Though it makes far less sense with postcode-only search, it is far more useful when you can search by name or part of the name - where typing only part of name/address is far more likely to be useful.

I guess that someone used this because this was the standard search menu or maybe it was planned/expected that general search by name will be added in the future.

**Comment by matkoniecz** [comment]
>  Yes for location issue it is just to change the text where it currently says' building information link.

It seems to change meaning of the field - right now it seems to allow giving any website where more info will be found

**Comment by matkoniecz** [comment]
so should I rename or hide that field or remove it entirely?

**Comment by polly64** [comment]
oh sorry meant that about dropdown. Yes keep the link but just change the text

**Comment by matkoniecz** [comment]
label size adjusted, #1015

**Comment by matkoniecz** [comment]
replaced by #1057
