### ISSUE TITLE
need to block discussion

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1011]
Hi @matkoniecz, @mdsimpson42  or @tomalrussell can you block discussion over holiday re check last post?

**Comment by matkoniecz** [comment]
I have no admin rights over repository, so I cannot change it.

Though while this comment was ugly obnoxious porn spam scam - it was quickly removed.

Maybe even by GitHub itself - i only got notification on multiple repositories hit by this wave and in almost all cases it was deleted before I opened it.

And sadly, any open discussion forum will have some level of spam.

**Comment by polly64** [comment]
Many thanks Mateusz and happy new year.i looked on the discussion to see if I could remove and had gone by then so really good to see GitHub removed. Let me know when you’re working next so we can discuss if you can release onto main site, as staging weirdly taking so long to load on my new mac

From: Mateusz Konieczny ***@***.***>
Date: Saturday, 31 December 2022 at 10:05
To: colouring-cities/colouring-london ***@***.***>
Cc: Polly Hudson ***@***.***>, Author ***@***.***>
Subject: Re: [colouring-cities/colouring-london] need to block discussion (Issue #1011)

I have no admin rights over repository, so I cannot change it.

Though while this comment was ugly obnoxious porn spam scam - it was quickly removed.

Maybe even by GitHub itself - i only got notification on multiple repositories hit by this wave and in almost all cases it was deleted before I opened it.

And sadly, any open discussion forum will have some level of spam.
