### ISSUE TITLE
can we change title?

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1013]
Hi @matkoniecz can we remove the 'current' on 'current planning applications'  in past application section? as getting confusing with 'current applications'
<img width="434" alt="Screenshot 2023-01-03 at 16 38 22" src="https://user-images.githubusercontent.com/42236514/210400938-13caccc7-ba23-48e6-99ee-8e455b5adb39.png">

**Comment by matkoniecz** [comment]
@polly64 Can we remove it in both sections?

**Comment by matkoniecz** [comment]
Or maybe set in both to "Last reported (...)"
