### ISSUE TITLE
White screen (uncaught error) on login

### ISSUE THREAD

**Issue by tomalrussell** [colouring-cities/colouring-london#1024]
**Describe the problem**
Logging in to the site leads to a white screen. Refreshing the page leaves the user successfully logged in.

**To Reproduce**
Steps to reproduce:
1. Go to colouring.london
2. Click on the Menu > Log In
3. Enter username and password correctly
4. Click 'log in'
5. See complete white screen
6. Back button does nothing
7. Refresh button is a successful workaround

**Expected behavior**
Log in successfully, get redirected to account page.

Errors should also be handled with a react error boundary, so we can at least show a message and suggest refreshing the page or linking back to the homepage.

**Logs**

Error in console:
```
TypeError: right-hand side of 'in' should be an object, got null
    render route.tsx:48
    n.prototype.render/$< react-router.js:445
    React 6
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    d auth-context.tsx:35
react-dom.production.min.js:216:199
```

**Comment by tomalrussell** [comment]
Note that this reproduces reliably when starting from the home page and navigating to log in. 

Just logging out from "my account" and logging back in seems to be successful, and starting from https://colouring.london/login.html (even in a new private tab) also works okay.

**Comment by matkoniecz** [comment]
we had similar problem some time ago...

**Comment by matkoniecz** [comment]
https://github.com/colouring-cities/colouring-london/pull/879 https://github.com/colouring-cities/colouring-london/issues/842

**Comment by tomalrussell** [comment]
Yes - here's the tricky line:

https://github.com/colouring-cities/colouring-london/blob/df1da50a4a23842b96296b16c96a7cd7bddbe0f4/app/src/frontend/route.tsx#L42

But `typeof null` is `"object"` so we need a more robust check:

```js
 if (typeof state == 'object' && state !== null && 'from' in state){ 
```
