### ISSUE TITLE
Put planning controls and Energy performance titles on single line in edit panel

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1030]
@matkoniecz can you Put planning controls and Energy performance titles on single line in edit panel
<img width="1419" alt="Screenshot 2023-01-10 at 09 32 23" src="https://user-images.githubusercontent.com/42236514/211514867-5d1bed46-ba83-4667-bdc3-a5a631b7e2a3.png">

**Comment by matkoniecz** [comment]
fixed by #1028
