### ISSUE TITLE
delete section from 'Age and history'

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1042]
@mdsimpson42 I forgot we need to delete this whole section from 'Age and History' except that could you move  just the historical land use category to  'Survival and loss'  below the three options for levels of survival

<img width="449" alt="Screenshot 2023-01-11 at 00 59 25" src="https://user-images.githubusercontent.com/42236514/211693758-ffc1ddfc-b2f9-420e-9943-445858eac562.png">

**Comment by mdsimpson42** [comment]
Fixed in commit cd1184c
