### ISSUE TITLE
add single word to two items

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1045]
@matkoniecz @mdsimpson42 could you add 
Please add '**the** last 12 months'
<img width="183" alt="Screenshot 2023-01-11 at 22 42 59" src="https://user-images.githubusercontent.com/42236514/211934285-c04deeae-1e17-4298-935b-2c3110987eda.png">

please add 'to **_the_** GLA's'
<img width="340" alt="Screenshot 2023-01-11 at 22 42 30" src="https://user-images.githubusercontent.com/42236514/211933864-e7dc9108-e8ee-4bde-a27a-4d569659442a.png">

**Comment by matkoniecz** [comment]
@polly64 Should it be added also in tooltips like
![screen](https://user-images.githubusercontent.com/899988/212019983-d6dc62e7-2779-4482-8b14-322a87bef39c.png)
?

**Comment by polly64** [comment]
@matkoniecz Great idea

**Comment by polly64** [comment]
@matkoniecz what would this say?

**Comment by matkoniecz** [comment]
@polly64  "by the Greater London Authority (GLA)"? "the GLA official description"

**Comment by polly64** [comment]
@matkoniecz yes good

**Comment by polly64** [comment]
@matkoniecz yes please add

**Comment by matkoniecz** [comment]
is the needed also in alt text of the logos image? The current text is

> Colouring London collaborating organisations: The Bartlett UCL, Ordnance Survey, Historic England, Greater London Authority

the primary use here is for dictation by screen readers for blind people

**Comment by polly64** [comment]
@matkoniecz @fallipalaiologou - again we need to record in report. Yes, and should  say ' Colouring London collaborating organisation _include_ ...... and add LOUGHBOROUGH UNIVERSITY (weirdly wants to go in caps) and Newcastle University

**Comment by mdsimpson42** [comment]
Should we close the issue if this has been done?

**Comment by matkoniecz** [comment]
I guess it can be closed (implemented, not merged - will be merged in one group with other fixes)
