### ISSUE TITLE
what is definition of a 'current application?

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1046]
Hi @matkoniecz  can you give me the description of a 'current' application? is it _one that is not yet been approved or has taken over 12 months to make a decision on_?

**Comment by matkoniecz** [comment]
Right now it is decided in https://github.com/colouring-cities/colouring-london/blob/master/app/src/frontend/building/data-containers/planning.tsx#L36-L49 and one other place which should have matching definition.

So it is considered as archived if
 - decision date is set and it is over one year ago
 - registration date with local authority is set and it is over one year ago

If neither applies then it is current.

So current ones are with decision date less than year ago and registration data less than year ago.

(or, in pathological cases: with both dates missing)

**Comment by matkoniecz** [comment]
I can give some examples how it works in practice or provide more info if needed.

Also, this definition can be changed if needed.

Let me know if either is needed, for now I closed it as answered.

**Comment by polly64** [comment]
@matkoniecz thanks let me have a think we might want to make it a little clearer in text will get back later

**Comment by polly64** [comment]
@matkoniecz could you give  examples below might be useful

**Comment by polly64** [comment]
@matkoniecz 

Can I clarify So current ones are with decision date less than year ago **and** with a registration data less than year ago.

**Comment by matkoniecz** [comment]
yes

with "data not provided" treated as "less than year ago"

**Comment by polly64** [comment]
@matkoniecz can you give me a suggestion of the exact wording you'd suggest we put?
not sure I understand about 'if data not provided'

**Comment by matkoniecz** [comment]
>  not sure I understand about 'if data not provided'

GLA data may provide "registered with local authority date" info or it can be an empty field without provided data

**Comment by polly64** [comment]
how do we know when to move these  to the past applications? could we have v old ones in there? do we need to have a '12 months after they cam into our system  anything with no registration date gets moved  to past?'

**Comment by matkoniecz** [comment]
> how do we know when to move these to the past applications? 

Based on dates in dataset - when applications are displayed their dates are checked and entry is classified as old or recent

> could we have v old ones in current with no date?

In theory yes.

But out of 431 535 only 2 have registered_with_local_authority_date field unset - and both of them have decision_date set.

So in practice it is not a problem.

> do we need to have a '12 months after they come into our system anything with no registration date gets moved to past?'

No, as right now it is purely theorethical.

**Comment by polly64** [comment]
@matkoniecz @fallipalaiologou  thanks this is very helpful and we need to record in the manual report. I won't then include in 'How to' as will just confuse people and as you said very rare occurrence
