### ISSUE TITLE
at least some Hackney planning links are relative

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-london#1047]
https://cl-staging.uksouth.cloudapp.azure.com/view/planning/1097095

Note how link goes to nonexisting page within the Colouring website itself.

![screen02](https://user-images.githubusercontent.com/899988/212027442-cf757d56-6fa3-4ef5-8491-f121a6a313ee.png)

This is a bad data in the source but may be fixable.

**Comment by polly64** [comment]
@matkoniecz do u think fixable now or in second phase

**Comment by matkoniecz** [comment]
should be reasonable to do now

**Comment by matkoniecz** [comment]
main thing is tracking down how link should be formatted - and is there any actual target to link

**Comment by polly64** [comment]
@matkoniecz fab
