### ISSUE TITLE
add pink button and key for Lifespan section

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1050]
@mdsimpson42 could you add a pink button and key for the lifespan section under age and history

**Comment by mdsimpson42** [comment]
I have added a pink "Click her to show historical maps" button under the "Lifespan" header, copied from "Survival and Loss"  

![image](https://user-images.githubusercontent.com/21125422/212878789-501dcbcb-45a7-49a4-9141-21fce67c1200.png)

I will try and add a key that replaces the current key when historical maps are added, but I'll do that as a separate issue.

**Comment by polly64** [comment]
@mdsimpson42 hi mike can't see on live site or see key is it on staging?- could you possibly also email staging link as lost as changed computer?

**Comment by mdsimpson42** [comment]
I've checked the changes in, but they're not deployed yet (so the screenshots are from the version on my machine). I will create a Pull Request later today with all of the changes in it, and then we can deploy them all at once.

**Comment by polly64** [comment]
@mdsimpson42 thanks Mike I'm working with Mateusz today so that would be great

**Comment by matkoniecz** [comment]
deployed some time ago
