### ISSUE TITLE
how do i get back from historic buildings to planning applications

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1052]
@matkoniecz can you test going from clicking on protected buildings map to getting back to planning applications- think we need to make this a bit easier . Reverts to 'empty map' if i go from planning then click heritage layer, then click off heritage layer.

I think if you click on heritage layer then click off it should revert to planning applications not empty map. Also maybe we should add a pink button in planning section as no way you can easily turn planning layers on other than via key?

Also can we deploy the revised switch on/off labels?

Should planning be loading more slowly than other layers because it is streamed?

can you make link in Menu to open manual

**Comment by matkoniecz** [comment]
Should be fixed now, let me know if that closed issue or other is still a problem.

![Peek 2023-01-21 16-45](https://user-images.githubusercontent.com/899988/213874772-6e73c312-adef-43bc-81d0-b1668cbe04e7.gif)
