### ISSUE TITLE
Tuquoise highlight too thin to see 

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1053]
Hi @matkoniecz turquoise highlight v thin on my screen can we make a bit thicker? 
<img width="489" alt="Screenshot 2023-01-16 at 11 18 11" src="https://user-images.githubusercontent.com/42236514/212666320-b54a3120-9970-4279-b19a-83dcb5ef3d51.png">

**Comment by matkoniecz** [comment]
I bet that something went wrong with supporting high-resolutions displays in highlight layer.

Will look into this.

**Comment by matkoniecz** [comment]
Is it happening with all layers and all buildings? Or only with some?

On which computer it happens? (device model)

![screen](https://user-images.githubusercontent.com/899988/212801112-3572584d-ad9d-4784-9648-6486916c5677.png)

**Comment by matkoniecz** [comment]
https://leafletjs.com/reference.html

> detectRetina
> If true and user is on a retina display, it will request four tiles of half the specified size and a bigger zoom level in place of one to utilize the high resolution.

and as outline is of a fixed size, it results in a smaller outline on retina displays, presumably removing it would result in expected size of outline but pixelated what would be unwanted but in a different way (I am guessing here that `detectRetina` matters, I will test it) ...

**Comment by matkoniecz** [comment]
@polly64 Is it currently a problem or not? (checking either live production site or staging will work)

**Comment by polly64** [comment]
@matkoniecz fine for now thanks
