### ISSUE TITLE
Loading/freezing  problem

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1057]
@tomalrussell @matkoniecz @mdsimpson42 
Hi all I'm having real trouble zooming in and out without the map freezing and concerned re presentation next week. Have change my Mac and am using 2 other computers to test. my new Macbook particularly bad regardless of browser or location  but actually no worse than on Dell tested with Turing IT at Turing yesterday- is there anything we can do to make loading faster?

**Comment by matkoniecz** [comment]
@polly64 Is it seeming to be fixed now? At least when site is not under heavy load by many concurrent users?

We could try testing how it works with many people requesting tiles at once (or we will see during the meeting).

**Comment by polly64** [comment]
@matkoniecz the good news is that even though internet is v bad where i am it is working on both machines ok!

**Comment by polly64** [comment]
@matkoniecz could u add new issue though to the phase 2 section re testing/tracking/improving performance

**Comment by matkoniecz** [comment]
added to https://github.com/colouring-cities/colouring-london/issues/1010

>  further improve performance - see Loading/freezing problem #1057 - including also budget focused performance allowing to use cheaper servers
