### ISSUE TITLE
Problem with reset password

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1058]
hi @mdsimpson42 report of reset password problem 
copying @matkoniecz  too

**Comment by mdsimpson42** [comment]
For context - email (09:58 on 18/01) 

User tried to create an account, was told the email address is already used for an existing account, tried to reset password but had no response.

**Comment by mdsimpson42** [comment]
The only reason the email would be in the database is if they have already registered, or if they were added (did we create an account for them so that they would have access?

**Comment by polly64** [comment]
@mdsimpson42 no think Theodor just made account but emailing him now as not sure of GitHub username

**Comment by traveller195** [comment]
hello everyboy,

yes, thanks for discussing my issue.
Now, I tried it again. And I got the same response:
for my email adress there is the message in a red box "Email already registered".

But also the "forgotten password?" function is not working well. So, I did not receive an email to be able to change password or something. Also not in junk folder.

And I think, I have not used this email in the past to sign up... but maybe, I forgot ;-) I am not sure.

best,

**Comment by mdsimpson42** [comment]
I've had a quick look at the database, I can confirm there is a user with that email address, registered on 2022-04-11 (with your username). I can only assume that you created an account, or that one was created for you.

As for why the Password Reset isn't working, I'm not sure how it works myself, but I will try to look into it. Was the feature working previously?

**Comment by matkoniecz** [comment]
> As for why the Password Reset isn't working, I'm not sure how it works myself, but I will try to look into it. Was the feature working previously?

I remember problem with outgoing emails classified as a spam.

@traveller195 Have you checked spam folder?

**Comment by traveller195** [comment]
Update: so, now I remember at least my old username ... so I am able to login successfully to this account!

But this reset password problem is not solved, I guess.

**Comment by polly64** [comment]
@matkoniecz @mdsimpson42 I'm now locked out of password for Colouring London too

**Comment by matkoniecz** [comment]
@polly64 Have you tried resetting password? From a quick look I do not see such request in the database, with latest one apparently being traveller195.

**Comment by matkoniecz** [comment]
Code references:

`SELECT * FROM user_password_reset_tokens ORDER BY expires_on;`

`SELECT * FROM USERS WHERE user_id = 'SNIPPPED';`

https://github.com/colouring-cities/colouring-london/blob/e12b544503a5e5ba302387a8c2bddee1a5be514d/app/src/api/services/passwordReset.ts

**Comment by matkoniecz** [comment]
@polly64 Or is it maybe happening on staging?

**Comment by polly64** [comment]
@matkoniecz @mdsimpson42 yes tried password reset and got to work but odd also having a problem . Also noticed there is no password check which we need to add as I couldn't see if my password was correctly typed- Mike could you have a look at that?  At the top of discussion it now says I'm in bootstrap mode and ' all newusers' will be granted trust level one and have daily emails enabled. Does that just mean I will receive notifications of their discussion comments?

**Comment by polly64** [comment]
@matkoniecz I think I was in main site have tried now on staging and working with new password. how does someone change their email address?

**Comment by polly64** [comment]
@matkoniecz if i change my password on staging will it also change for live site?  How long does it take to reset? I just changed and now can't get in on staging with new password and can get in on live site with old password when prompted when i want to edit. But when I go to discussion it won't let me use the same password to edit

**Comment by polly64** [comment]
@matkoniecz says no account matches username AV64

**Comment by matkoniecz** [comment]
@polly64 

> if i change my password on staging will it also change for live site?

staging server, production server and forum have separate accounts

changing password on one of them has no effect on other accounts

> @matkoniecz says no account matches username AV64

on which one? Production server? Staging? Forum?

**Comment by polly64** [comment]
@matkoniecz can we have a quick chat online will invite you now

**Comment by matkoniecz** [comment]
@polly64 yes, we can do this

**Comment by matkoniecz** [comment]
@polly64 I am on the same meeting as in the morning (weekly meeting link)

**Comment by polly64** [comment]
Can you send link

From: Mateusz Konieczny ***@***.***>
Date: Friday, 20 January 2023 at 17:10
To: colouring-cities/colouring-london ***@***.***>
Cc: Polly Hudson ***@***.***>, Mention ***@***.***>
Subject: Re: [colouring-cities/colouring-london] Problem with reset password (Issue #1058)

@polly64<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpolly64&data=05%7C01%7Cphudson%40turing.ac.uk%7C85289ea6bf81421dcb1608dafb093c53%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638098314326147235%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fQwLug%2Fv1l9ObVrlWij34xmymtux7IQiQCEM0XfS5Ok%3D&reserved=0> I am on the same meeting as in the morning (weekly meeting link)

**Comment by matkoniecz** [comment]
send

**Comment by traveller195** [comment]
@polly64  @matkoniecz 
Update:
Fortunately, I got this reset password email yesterday (20th of January 2023) 6:04 pm ... it was not classified as spam
thanks :-)

**Comment by polly64** [comment]
@traveller195 thanks for update

**Comment by tomalrussell** [comment]
Great, thanks @traveller195 ..the fix for you was setting a couple of MX records so the ioer.de mail server would accept the message - I triggered another password reset request for you around that time yesterday.

**Comment by matkoniecz** [comment]
So it seems that it is fixed? Should we close this issue?

**Comment by polly64** [comment]
@tomalrussell what do you think?

**Comment by tomalrussell** [comment]
Yes, original problem looks fixed to me.
