### ISSUE TITLE
Planning zones needs hperlink to GLA London planning hub in the Planing hub text in the blue box

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1060]
@matkoniecz Planning zones needs hyperlink to GLA London planning hub for related text in the blue box for this section

**Comment by polly64** [comment]
@matkoniecz can we meet now?

**Comment by matkoniecz** [comment]
@polly64 I have in my notes that it was supposed to also go into gray disclaimer.

Do we want it in both places or only one?

![screen](https://user-images.githubusercontent.com/899988/213874543-7e9bc6f6-09df-4070-82e9-2f27cef4a6c7.png)

Should I add linked mention of the GLA in "Current/active applications (official data)" blue box?

**Comment by polly64** [comment]
@matkoniecz umm we don't actually mention the GLA in the current /active applications now. 

- we need to copy the past application disclaimer to the current application disclaimer as well as the current has lost the critical top section. so for past and current it should read'  _Planning application status is streamed using live data uploaded by local authorities to the Greater London Authority's Planning London DataHub.
Disclaimer: Not all applications for London are displayed. Some boroughs do not yet provide planning data to the GLA. For comprehensive information on applications please visit the relevant local authority's planning website.'_
-  In each of theabove  disclaimers the link should be on the words 'Greater London Authority's Planning London Datahub'
- Datahub should be spelt like this i.e _without_ the capital on Hub- in each 
- Under Planning zones the disclaimer should read   _Planning  zone information is accessed from the Greater London Authority's Planning London DataHub.'_ with the same words highlighted as above and linked
- Under designation we actually should add a new disclaimer box under the blue box to read
- _Data for designated heritage assets has been accessed from the National Heritage List for England managed by Historic England. Conservation area data can also be accessed here (give link to Ian hall page). For comprehensive information please also visit the relevant  local authority's website_'.
-

**Comment by matkoniecz** [comment]
> we need to copy the past application disclaimer to the current application disclaimer as well as the current has lost the critical top section
>  Planning application status is streamed using live data uploaded by local authorities to the Greater London Authority's Planning London DataHub.

this is still shown for sections with planning application that can be displayed, for example see say

![screen](https://user-images.githubusercontent.com/899988/213907746-04b8d731-c79b-4767-96e5-a71cff000916.png)

**Comment by matkoniecz** [comment]
> In each of theabove disclaimers the link should be on the words 'Greater London Authority's Planning London Datahub'

Would be OK to include also "the" in a link?

![screen02](https://user-images.githubusercontent.com/899988/213908830-ed5c031f-48e3-42d8-9fc1-266cdd7cba3b.png)

**Comment by matkoniecz** [comment]
> Datahub should be spelt like this i.e without the capital on Hub- in each

OK, will change it (was in few place, I think I got all of them)

**Comment by matkoniecz** [comment]
> Under designation we actually should add a new disclaimer box under the blue box to read
> Data for designated heritage assets has been accessed from the National Heritage List for England . Source information for Conservation Area data can be accessed here (give link to Ian hall page). Please note all data should be double checked against official sources where used for planning purposes'.

Should we link something in "National Heritage List for England"?

**Comment by polly64** [comment]
@matkoniecz yes great

**Comment by polly64** [comment]
@matkoniecz  yes 'the' should be added to the Greater London Authority

**Comment by matkoniecz** [comment]
> yes 'the' should be added to the Greater London Authority

So this part should be fixed? See

https://colouring.london/view/planning/2481763

![screen03](https://user-images.githubusercontent.com/899988/213910134-51f0423a-77a8-4d4f-b362-a07c3fbfd749.png)

**Comment by matkoniecz** [comment]
Can you confirm that it is the expected view? If yes then I will close this issue and open new ones for not yet fixed related ones.

**Comment by polly64** [comment]
@matkoniecz ah i see it says 'live data'. we need to change on all discalimers  to 'streamed data'. Otherwise all good

**Comment by matkoniecz** [comment]
Then I will close this one, fix DataHub to Datahub, open https://github.com/colouring-cities/colouring-london/issues/1065 (and fix it).

One thing is not clear -is it fine to display shortened disclaimer when there is no data in a given section? Or should it be always in the long form?

**Comment by polly64** [comment]
@matkoniecz sorry can you copy shortened disclaimer

**Comment by matkoniecz** [comment]
shorter when section has no entries

> Disclaimer: Not all applications for London are displayed. Some boroughs do not yet provide planning data to the GLA. For comprehensive information on applications please visit the relevant local authority's planning website.

longer when section has some entries

> Planning application status is streamed using live data uploaded by local authorities to [the Greater London Authority's Planning London DataHub](https://www.london.gov.uk/programmes-strategies/planning/digital-planning/planning-london-datahub).
> Disclaimer: Not all applications for London are displayed. Some boroughs do not yet provide planning data to the GLA. For comprehensive information on applications please visit the relevant local authority's planning website.

**Comment by polly64** [comment]
@matkoniecz yes that's good thanks
