### ISSUE TITLE
clear layers- can we make it also clear listed building and conservation layers if activated in the editing section

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1064]
@matkoniecz remebered we wre also going to look at green red colours instead of pink buttons- I don't think urgent now as we'll also have to check all the text but what would be good would be to be able to clear all layers using the clear layer button including if you've left the listed building and conservation layers on in your editing section

**Comment by matkoniecz** [comment]
@polly64 

What should happen with ones that have no clear on/off state? Such as layer switchers? Be always off? Be always on? Stay pink and increase colour variety that may start going into cacophony?

**Comment by polly64** [comment]
@matkoniecz sorry what do you mean by leaving layer switches always off?
Also can you easily deploy all changes to staging - notice some aren't activated on it - as i think you said best to show the demo there in case multiple users impact on speed?

**Comment by polly64** [comment]
@matkoniecz maybe we should just leave pink button pink for now-

**Comment by matkoniecz** [comment]
> sorry what do you mean by leaving layer switches always off?

![Peek 2023-01-22 18-42](https://user-images.githubusercontent.com/899988/213931279-f037e983-165b-4848-840b-5f52a15302a1.gif)

bottom button would switch between red and green

but what should happen with upper one?

>  Also can you easily deploy all changes to staging - notice some aren't activated on it - as i think you said best to show the demo there in case multiple users impact on speed?

Yes, I will do this - likely today in the evening

**Comment by matkoniecz** [comment]
How it may look like:

![Peek 2023-01-22 19-09](https://user-images.githubusercontent.com/899988/213932473-865874d7-a8a2-4523-889e-54cb8c0fd3f5.gif)

it is now on https://cl-staging.uksouth.cloudapp.azure.com/

**Comment by matkoniecz** [comment]
@polly64 Can you test and let me know how you like this idea after being able to actually sue it? Work on it and tweak colours or roll it back?

**Comment by polly64** [comment]
@matkoniecz yes looks fine but can't see conservation area layer
