### ISSUE TITLE
Designation source info

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-london#1065]
https://github.com/colouring-cities/colouring-london/issues/1060#issuecomment-1399280520

> Under designation we actually should add a new disclaimer box under the blue box to read
> Data for designated heritage assets has been accessed from the National Heritage List for England . Source information for Conservation Area data can be accessed here (give link to Ian hall page). Please note all data should be double checked against official sources where used for planning purposes'.

@polly64 

Should we link something in "National Heritage List for England"?

**Comment by matkoniecz** [comment]
@polly64

Should we link something in "National Heritage List for England"?

**Comment by polly64** [comment]
@matkoniecz yes please

**Comment by matkoniecz** [comment]
@polly64 

What should be link target?

https://historicengland.org.uk/ or something else?

**Comment by polly64** [comment]
https://historicengland.org.uk/listing/the-list/

**Comment by matkoniecz** [comment]
![screen01](https://user-images.githubusercontent.com/899988/216320774-3b8633d4-4402-4b88-9ab4-f2171f590036.png)

**Comment by polly64** [comment]
@thanks can you take the hyperlink off the acronym. also noticed with Mile we don't seem to have th GLA activated in the current and past planning applications on live site
