### ISSUE TITLE
post codes on staging - search appears to not work well on staging and not on staging

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-london#1068]
@polly64 Can you provide some examples of ones leading to a bad location?

**Comment by matkoniecz** [comment]
@polly64 Can you provide example of post code that does not work? I tested with `SE1 7LY` and it appears to work as expected and leads to Waterloo station.

**Comment by polly64** [comment]
@matkoniecz on staging N195JS didn't work before

**Comment by matkoniecz** [comment]
hmm, it works now

**Comment by polly64** [comment]
@matkoniecz great

**Comment by matkoniecz** [comment]
lets close it and open if problem reappears
