### ISSUE TITLE
provide more info about CA

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-london#1071]
Descriptions provided by @polly64 have not fit into input fields so I tried alterbative:

----------------------------

link provided:

![screen02](https://user-images.githubusercontent.com/899988/216087598-2d4b08b9-a91f-4aaf-bd34-ae41fbd25711.png)

----------------------------

no link provided:

![screen03](https://user-images.githubusercontent.com/899988/216087667-e232cfd2-3af9-499e-a23b-459ac5d96738.png)

----------------------------

no link provided, we know it is in CA:

![screen01](https://user-images.githubusercontent.com/899988/216087778-42174c01-936f-4472-9cde-fd6243144100.png)

----------------------------

@polly64 Do you like this solution?

**Comment by polly64** [comment]
@matkoniecz yes let's try this thanks
