### ISSUE TITLE
Disaster (Resilience) - Disaster Dates

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-london#151]
Currently, the user is able to select a Start Date and End Date for a disaster. The calendar plugin seems to work but:

- [x] Formatting could be adjusted to add labels and make it more consistent with the rest of the site
- [x] Dates are currently not being stored in the database

**Comment by polly64** [comment]
@mdsimpson42 can you check and close if done

**Comment by mdsimpson42** [comment]
Yes, I believe I've fixed this. The changes have definitely been deployed to staging. I will confirm if they have been merged to master.
