### ISSUE TITLE
Add London 1940s aerial images and 1950s maps from NLS

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#16]
Hi @mdsimpson42 after construction and typology release can we (ideally by 3rd July london data week)

- [ ]  add the 1940s aerial imagery  from nls/chris fleet to our layer list 
- [ ]  add the 1940s/50s map layer to the Age and history survival section
- [ ] create a new section in age and history saying 'Historical map layers' and then just add buttons for all raster and vectorised historical layers in chronological order ads they come on board 
- [ ] we also need to add source links (below) for each map

 Links from National Library of Scotland @ChrisFleet

a) two 1940s air photo georeferenced layers covering London- 

1:1,250: [https://maps.nls.uk/geo/explore/#zoom=10.0&lat=51.54660&lon=-0.13280&layers=253&b=2](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.nls.uk%2Fgeo%2Fexplore%2F%23zoom%3D10.0%26lat%3D51.54660%26lon%3D-0.13280%26layers%3D253%26b%3D2&data=05%7C01%7Cphudson%40turing.ac.uk%7C266715e6d45c48b1614808db6819f05c%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638218232857015713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aUWIe6m974zks8xG%2BxrrF1l1Iefbp%2FGW%2BFHtZz9zX5E%3D&reserved=0)

1:10,560: [https://maps.nls.uk/geo/explore/#zoom=10.0&lat=51.54034&lon=-0.04399&layers=9&b=2](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.nls.uk%2Fgeo%2Fexplore%2F%23zoom%3D10.0%26lat%3D51.54034%26lon%3D-0.04399%26layers%3D9%26b%3D2&data=05%7C01%7Cphudson%40turing.ac.uk%7C266715e6d45c48b1614808db6819f05c%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638218232857015713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F1tibxOhon9qDEUiw4QN2wqakaIfhWTVd%2F6tdEgBahY%3D&reserved=0)
 
(gaps in both of these layers, but they are still good coverage)

b) 1940s/50s layer
 
The OS 1:1,250 topographic mapping in the 1940s-1950s layer is at:
 
[https://maps.nls.uk/geo/explore/#zoom=10.0&lat=51.54034&lon=-0.04399&layers=170&b=2](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.nls.uk%2Fgeo%2Fexplore%2F%23zoom%3D10.0%26lat%3D51.54034%26lon%3D-0.04399%26layers%3D170%26b%3D2&data=05%7C01%7Cphudson%40turing.ac.uk%7C266715e6d45c48b1614808db6819f05c%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638218232857015713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uhxj94FID3BMroql481tcgrhC7OfWi%2BYXOe7RZcJIjY%3D&reserved=0)
 
Guide at [https://maps.nls.uk/guides/georeferencing/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.nls.uk%2Fguides%2Fgeoreferencing%2F&data=05%7C01%7Cphudson%40turing.ac.uk%7C266715e6d45c48b1614808db6819f05c%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638218232857015713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o9sByhSSHlSdgBATS3edlEKQChZGsKpIdSOXBUqftzI%3D&reserved=0) on how to find our tileset URLs for adding into Colouring London, etc.,

**Comment by mdsimpson42** [comment]
I've been able to get the two 1940s air photos working (a), but I can't find the right image URLs for the topographic maps (b). There doesn't seem to be a single overlay layer that has all of London on it, and one of the overlay links produces a Google Maps error.
