### ISSUE TITLE
@MKIM1008 not showing in assignee list

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#175]
Hi @matkoniecz, @MKIM1008 and @taimaz22 not showing in assignee list could you add thanks

**Comment by matkoniecz** [comment]
I invited them with read level access. I can also give them right to open, close, label issues and pull requests.

Note that they need to accept invites.

**Comment by polly64** [comment]
Thanks could you give access to open and close as well

**Comment by matkoniecz** [comment]
Done! Upgraded role to "triage" giving access to issue management.

Also, MKIM1008 accepted invitation, @taimaz22 not yet.

**Comment by matkoniecz** [comment]
Also, assigning in this repository now works for our new member:

![screen](https://github.com/colouring-cities/colouring-london/assets/899988/514c2914-4ec8-40f9-9acf-df35da9a340d)
