### ISSUE TITLE
Replace deprecated componentWillReceiveProps

### ISSUE THREAD

**Issue by mz8i** [colouring-cities/colouring-london#199]
PR colouring-cities/colouring-core#417 included code using a deprecated handler `componentWillReceiveProps`. This should be replaced with a different mechanism.

**Comment by polly64** [comment]
@matkoniecz can you close?

**Comment by matkoniecz** [comment]
yes, grepping and searching on github has not found such text in code

**Comment by matkoniecz** [comment]
BTW, this also was issue affecting colouring-core in general (all source code unless London specific would fit rather `colouring-core` repository)
