### ISSUE TITLE
survival map issues 

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#22]
@mdsimpson42 
- [x] reduce size of red lines on survival map as you zoom out
- [ ] check issue with adding and copying edits and then being redirected to ~~s~~age and history subtitles rather than back to survival section 
- [x] ~~some issue of moving to other categories and can't get rid of survival map easily~~
- [ ] edit history showing edit date overriding building age date - needs to be separated
- [ ] ensure survival map shuts when opening other maps

**Comment by mdsimpson42** [comment]
> reduce size of red lines on survival map as you zoom out

Line colour and thickness at various Zoom levels have now been changed.

**Comment by mdsimpson42** [comment]
> some issue of moving to other categories and can't get rid of survival map easily

Already an issue: https://github.com/colouring-cities/colouring-core/issues/1141

**Comment by polly64** [comment]
@mdsimpson42 when you've copied and pasted and you click back it goes to main age and history option though I want to just go back to survive. 

<img width="811" alt="Screenshot 2023-09-19 at 14 23 19" src="https://github.com/colouring-cities/colouring-london/assets/42236514/5fb0a9a3-efcc-47c7-a574-c12e3644e891">
<img width="619" alt="Screenshot 2023-09-19 at 14 23 24" src="https://github.com/colouring-cities/colouring-london/assets/42236514/893612c3-2501-4a98-b0df-af7297e94cc6">

Re the age data. re copy and pasting survival status it will show a blue tick for the option for status of demolition and also for source type, but it will then  automatically add in the building age. We don't want this because we are just wanting to copy and paste survival. If we copy and paste date the dates will be wrong. We need to also remove all age data  that has been added through this survival feature as most of this will be wrong

**Comment by polly64** [comment]
@mdsimpson42 is this done or should we refer to MK?
