### ISSUE TITLE
Investigate building update speed in API

### ISSUE THREAD

**Issue by mz8i** [colouring-cities/colouring-london#223]
It seems that updating a building through API is rather slow. This is problematic for bulk imports like the Turing computational generation dataset, with 100,000s records to update.

Investigate:
- [ ] which part of the update process takes most time
- [ ] could we change anything to improve bulk update performance? For example, the tile cache is partially cleared upon a building update. Do the file system operations take too much time? Could we decouple the process, and only mark the cached tiles as out-of-date, rather than actually deleting them from disk? The cached tiles could then be cleared on a schedule of a couple of seconds, or whenever a tile is requested that is marked as out-of-date.

**Comment by matkoniecz** [comment]
I was doing some tests and it was not blindingly fast but also was not terribly slow.

If that is problem it will surface during testing bulk upload tool, see https://github.com/colouring-cities/colouring-core/issues/815

**Comment by matkoniecz** [comment]
` @polly64 polly64 transferred this issue from colouring-cities/colouring-core Jan 9, 2024 `

Though I would consider transferring it back, it is `core` issue not specific to London.
