### ISSUE TITLE
"the Colouring Cities Research Programme (CCRP)  The Colouring Cities Research Programme (CCRP)" in intro

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-london#42]
Comes from https://github.com/colouring-cities/colouring-london/blob/master/app/src/frontend/pages/welcome.tsx#L22 and https://github.com/colouring-cities/colouring-london/blob/master/app/src/cc-config.json#L3

visible at https://colouring.london/

**Comment by polly64** [comment]
@matkoniecz would you possibly be able to look at this? I have to give a presentation Monday

**Comment by matkoniecz** [comment]
I will do this today or tomorrow

**Comment by matkoniecz** [comment]
@polly64 

Is 

> Colouring London is also the prototype for the The Colouring Cities Research Programme (CCRP), led by the Alan Turing Institute. It involve an international consortium of academic institutions involved in building research.

OK?

Or would 

> Colouring London is also the prototype for the The Colouring Cities Research Programme (CCRP), led by the Alan Turing Institute, involving an international consortium of academic institutions involved in building research.

or something similar would be better?

(also, maybe "involve" repetition would be nice to remove)

**Comment by matkoniecz** [comment]
https://colouring.london/ now has a temporary fix:

![screen](https://github.com/colouring-cities/colouring-london/assets/899988/3269924b-e0e1-4084-95c1-7c741bac779c)

**Comment by polly64** [comment]
@matkoniecz thank you so much for this

**Comment by mdsimpson42** [comment]
This change had not been made on the master branch of the main repository. I have tweaked the wording to be more consistent with the Core Platform (and removed the "the The" typo). I'll deploy this to Main later this week.

**Comment by polly64** [comment]
@mdsimpson42 thanks deployment of this is a bit of a priority because people landing on it

**Comment by mdsimpson42** [comment]
Changes have now been merged and deployed
