### ISSUE TITLE
db:  Add Community category to database

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-london#432]
**Fields for launch**
- Ownership type
- Ownership perception
- Historic ownership

**Steps for adding new fields to database;**

- [x] Identify bulk data sources (Function Sties and London Development Database)
- [x] Required - Define field values as static category page
- [ ] Required - Identify need for source and verification for fields, log to spreadsheet
- [x] Required - Define input method for field (Drop down / Autocomplete with autofill?) 
- [x] Required - Code category down file
- [x] Required - Code category up file
- [x] Required - Test category down file
- [x] Required - Test category up file
- [x] Required - Add category down file
- [x] Required - Add category up file
- [x] On completion set up Github issue for activating fields on front end see #433

**Comment by edwardchalstrey1** [comment]
Hi @dominijk can this be closed? Also for any other open issues you may have on the project :)

**Comment by dominijk** [comment]
@edwardchalstrey1 the unhelpful answer is I'm not sure, i've not been directly involved with the project since early 2020. No issue my side on closing my authored issues
