### ISSUE TITLE
SUSTAINABILITY 

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-london#435]
toxicity ratings #352
disability access #315

**Dependencies** 
Run sustainability (011) migrations 

**What UI does**
Allows input of alphabetical value A-G only for field name `DEC Grade` which inputs to db field `sust_dec`. Tooltip should read "Display Energy Certificate"  

**What map looks like**
For launch on category load this will be the `sust_dec` field. This is based on the UK GOV standard  traffic light colour palette (for launch) longer term we might want to change colour palette to something which is accessible. 

- 'A' `#007F3D`
- 'B' `#2C9F29`
- 'C' `#9DCB3C`
- 'D' `#FFF200`
- 'E' `#F7AF1D`
- 'F' `#ED6823`
- 'G' `#E31D23`

**Comment by dominijk** [comment]
Front end copy for UI 

field label | tool tip | db_field | active
-- | -- | -- | --
BREEAM rating | (Building Research Establishment Environmental Assessment Method) May not   be present for many buildings | sust_breeam_rating | yes
DEC Rating | (Display Energy Certificate) Any public building should have (and   display) a DEC. Showing how the energy use for that building compares to   other buildings with same use | sust_dec | yes
EPC   (Rating) | (Energy Performance Certifcate) Any premises sold or rented is required   to have an EPC to show how energy efficient it is. Only buildings rate grade   E or higher maybe rented | sust_aggregate_estimate_epc | no
Last   significant retrofit | Date of last major building refurbishment | sust_retrofit_date | yes
Expected   lifespan for typology | We will be calculating this field base on buildings with similar typology   and use | sust_life_expectancy | no
Typical   actual life expectancy for typology/construction materials and method | We will be calculating this field base on buildings with similar typology   and use and data on demolitions | sust_lifespan_average | no
Embodied   carbon estimation for typology/size | This is an estimate of embodied carbon for this building   typology/construction type/size without retrofit | sust_embodied_carbon | no

**Comment by mz8i** [comment]
@dominijk could I ask for additional details for the fields (also applicable to other categories): input type (numeric, dropdown etc), limitations (e.g. min/max or list of options)

**Comment by dominijk** [comment]
@mz8i sure, for the `enums` do you want a list of the options?

**Comment by mz8i** [comment]
Ideally yes, please, it's just so that it's quicker to get that information than to deduce from the migrations

**Comment by dominijk** [comment]
@mz8i added via edit to the above

**Comment by mz8i** [comment]
I like how the minimum year is the issue of Domesday Book :)

**Comment by dominijk** [comment]
I don't think any earlier data exists but maybe some Roman buildings changed use and some hardcore classics historian has a text and will want to record this, but that's a definite edge case!

**Comment by mz8i** [comment]
@dominijk I can see the migration contains fields like embodied carbon but they are not in the list. I assume we don't want to display them for now?

**Comment by dominijk** [comment]
@mz8i correct as the active column this should be disabled on the web interface for now

**Comment by mz8i** [comment]
@dominijk I will leave these fields out of the interface for now. If you want me to add them, please can you amend the above table to include the missing fields

**Comment by polly64** [comment]
June 2020 to do list

1. @dining-liu Add BREAM data


l links https://github.com/colouring-london/colouring_london_analysis/tree/Sustainability/BREEAM
