### ISSUE TITLE
Update node and postgres

### ISSUE THREAD

**Issue by tomalrussell** [colouring-cities/colouring-london#531]
> I was thinking it might be good to update Node and Postgres to latest stable version at some point soon [...] For Node that would be 12.13.1, and Postgres - 12.1

@mz8i in https://github.com/tomalrussell/colouring-london/pull/530#issuecomment-564003547_

- [x] Update node to 12.14.1 in dev
- [x] Update postgres to 12 in dev
- [x] Update postgis to 3 in dev
- [x] Run automated tests, check app starts, renders tiles, responds
- [x] Update node version to 12 in `.travis.yml`
- [ ] Update install instructions in `docs/setup*.md`
- [x] Update `provision/vm_provision.sh`
- [ ] Deploy to staging
- [ ] Deploy to production

**Comment by mz8i** [comment]
Currently, we are limited in terms of the PostgreSQL/PostGIS version by the packages available in the Ubuntu repository (10 / 2.4). I'd suggest adding the Postgres repo in order to have access to more recent versions (12 / 3) as shown [here](https://computingforgeeks.com/how-to-install-postgis-on-ubuntu-debian/) and [here](https://computingforgeeks.com/how-to-install-postgis-on-ubuntu-debian/). @tomalrussell are you fine with moving away from the Ubuntu repository to the Postgres one?

**Comment by mz8i** [comment]
Updated node incl. checking in dev and staging and docs update, and released to production. Postgres to follow in a separate PR

**Comment by tomalrussell** [comment]
Just to bump this - not urgent, but can confirm all looks fine in dev with PostgreSQL 12.3 and PostGIS 3.0.1 on Ubuntu 20.04 focal, from the Postgres apt repository (notes: https://www.postgresql.org/download/linux/ubuntu/).

**Comment by tomalrussell** [comment]
Note to self with node packages - some to update for node 14 (next LTS)

Check for new packages:

    npm outdated

Check and pick packages to update: 

    npx npm-check -u

**Comment by edwardchalstrey1** [comment]
@tomalrussell do you know what the situation with these is currently?

**Comment by tomalrussell** [comment]
@edwardchalstrey1 the latest LTS stack would be: Ubuntu 20.04, node 16, PostgreSQL 14, PostGIS 3. 

I think this should work fine for us with the major bump to pg-promise - https://github.com/colouring-cities/colouring-london/pull/671 - I'd be happy to help with user acceptance testing

See also @matkoniecz latest explorations on https://github.com/colouring-cities/colouring-london/pull/762

**Comment by edwardchalstrey1** [comment]
See problem with postgres 14 documented here: https://github.com/colouring-cities/colouring-london/pull/776#discussion_r811324120
