### ISSUE TITLE
Colouring Loughborough stage on check list 

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#57]
@matkoniecz @mdsimpson42 @fallipalaiologou @MKIM1008 @taimaz22

- [ ]      M_Kon: Change to Colouring Loughborough and alter landing text to read:

_Welcome to Colouring Loughborough!

Colouring Loughborough is a free knowledge exchange platform designed to provide over 100 types of open data on Loughborough's buildings to help improve their quality, efficiency, sustainability and resilience and to meet net-zero goals.

Colouring Loughborough is also the Colouring Britain regional demonstration site, and is part of the international [Colouring Cities Research Programme/CCRP](https://github.com/colouring-cities/colouring-cities.github.io). Teh CCRP is run by the Alan Turing Institute and provides open-source code for networked open data platforms providing open spatial data on the composition, performance and dynamic behaviour of the building stock. This is designed as a sustainable resource with new features and data added and improved on all the time.
 
At the moment data on buildings is very fragmented and also often heavily restricted. The Colouring Loughborough platform allows you to help the University and local authority build a free digital platform for the town that can help achieve sustainability goals, 

All our [data](https://colouringlondon.org/data-extracts.html) and [code](https://github.com/colouring-cities/colouring-core) are free to download, use and share under our open licence terms. Our [open manual](https://github.com/colouring-cities/manual/wiki) also provides non-technical information on the CCRP for anyone interested in our research.!

Colouring London is a free knowledge exchange platform designed to provide over fifty types of open data on buildings in the city, to help make the city more sustainable.

Colouring London is part Colouring Cities.  The Colouring Cities Research Programme (CCRP), led by the Alan Turing Institute, is [an international consortium of academic institutions](https://github.com/colouring-cities/colouring-cities.github.io) involved in building research. Our aim is to maximise accessibility to building-level data across countries, to help improve stock quality, efficiency, sustainability and resilience and meet net-zero goals.

New data and features are added all the time. We are keen to engage as many people as possible in platform development. Whether you are a resident, or a stakeholder in academia, government, industry or the third sector, any help you can give colouring in our Colouring Cities maps, and enriching and verifying our open databases with your knowledge, is greatly appreciated.

All our [data](https://colouringlondon.org/data-extracts.html) and [code](https://github.com/colouring-cities/colouring-core) are free to download, use and share under our open licence terms. Our [open manual](https://github.com/colouring-cities/manual/wiki) also provides non-technical information on the CCRP for anyone interested in our research._       

- [ ]     M_Kon: Demo of progress with Colouring Loughborough interface 

- [ ]       M_Kon: Discuss progress re use of OSMM to map Loughborough on staging - can we see? Need to keep these behind the firewall once use approved.

- [ ]       M_Kon/PH: Helpful to track amount of Azure credits used for Loughborough site - current plan to work with a university as part of Colouring Britain academic network who will will buy a server and manage the database so we are no longer on the Azure system and can cut these costs in the long run.

- [ ]      M_Kon: Discuss progress with testing of INSPIRE to split Open Map Local Upload for Charnborough /or E. Midlands Region - can we see sample?

- [ ]      M_Kon: Demo any EPC data provided by MKim if time

- [ ]      M_Kon/TL: Consider a short screen video showing insertion of these features as a demo to encourage engagement from stakeholders, and to produce quick demo screen videos as new features are built which you can blog about

-------------------------------------------------------------------------------------------------------

- [ ] #58
            streetblock level (i.e. for all buildings in a block so these will match with OS Open Map Local spatial units).

- [ ]      M_Kim: Show any open SME or land use open Datasets for Loughborough available ideally mapped using GIS

- [ ]      M_Kim & TL: Are we mapping land use using MSE data, or land use and SME information? 
             If both need to create new SME data class. How will this be updated? 

- [ ]      M_Kim and TL, Does the current Colouring Loughborough 'mixed use' feature under 'Land Use' also require
            an option for floor level for each different land use to be put in? 

- [ ]     M_Kim and TL: Do we want to track change of land use? If so we need to be able to add date 

------------------------------------------------------------------------------------------------------------

For subsequent meeting

-   MK: How could  moderated bulk upload potentially work?

-  All: Should we create email verification for sign in?

-  PH: Showcase/case study section - working with international teams

**Comment by MKIM1008** [comment]
> * [ ]       M_Kim: Show any open SME or land use open Datasets for Loughborough available ideally mapped using GIS.

1. I've discovered an SMEs dataset on Gov.uk and will bring it along this Wednesday for our review.
https://www.gov.uk/government/publications/companies-house-foi-responses-january-to-june-2022/a-list-of-small-and-medium-sized-enterprises-sme-in-the-uk
http://download.companieshouse.gov.uk/en_output.html

2. Regarding land use, are we able to use the data from DEC and EPC? If so, we should discuss how to effectively translate the land use codes to align with the current Colouring London's land use legend.
![image](https://github.com/colouring-cities/colouring-london/assets/88775529/2a09c5b2-5ece-47cd-b614-c8d4bbbae148)

Or can we create a new DEC / EPC (land use) legend? This opinion is from the meeting with Falli.

There's not enough land use data in OSM and I will review it more.

**Comment by polly64** [comment]
Hi @MKIM1008 @fallipalaiologou  @matkoniecz have added answers under M_Kim's  above. Can you add Taimaz' Github username so she's looked in

**Comment by MKIM1008** [comment]
EPC energy rating ![image](https://github.com/colouring-cities/colouring-london/assets/88775529/c9312db3-df6a-4d2c-8540-7e4a41cd8f73)

**Comment by polly64** [comment]
@MKIM1008 could you move any of these to relevant other Data issues or close them - I have written notes above - all energy stuff that is new to other energy items should go under Data: Energy main issues

**Comment by MKIM1008** [comment]
@polly64 I've completed mentioning the comments on other Energy issues and closed this issue.
