### ISSUE TITLE
Master Map polygons upload for Loughborough

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-london#63]
I received confirmation from @polly64 that we are allowed to use Master Map buildings polygons for Loughborough.

I want to let @mdsimpson42 that I am planning to upload the building for Loughborough, maybe today, and change tile coverage area to include both Loughborough and London (and merge https://github.com/colouring-cities/colouring-core/pull/1286 ).

**Comment by matkoniecz** [comment]
Building upload for Loughborough was tested on staging already and it worked fine.

**Comment by polly64** [comment]
Hi @matkoniecz can we release footprints onto live site? when is good for you to do this?

**Comment by matkoniecz** [comment]
@polly64 This should be fixed now both on staging and production: feel free to close it if fixed, please let me know what is wrong if fixed.

Note that staging may end not displaying buildings in lboro if version with different tile extend will be loaded there
