### ISSUE TITLE
LIVE STREAMING - planning data streaming

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#685]
**Purpose of Planning Viz feature:**

1.  To provide open code for a Colouring Cities feature that increases  accessibility to open planning data- demoed  for London using data released by the GLA
2.  To enable communities, developers,  local authorities, and others to gain instant  accessto visual  info onthe  location and status of planning applications, as well as weblinks to application details
3.  To collect information, on the location/rate and type of new build and demolitions occurring o provide live data on urban metabolism and on energy and waste flows 
4. To provide greater transparency on what is being approved/rejected and why? to understand how this links to sustainable planning policies, and what types of finite resource are being lost
6. To identify where appeals are occurring e.g. locations of conflict between communities and/or local authorities, and developers, to widen debate.
7. To provide live open data on housing completions 

 **Actions**
 @mz8i  @matkoniecz do add/adjust action list, and add any comments on issues which need to be discussed below

- [x] Assess https://www.london.gov.uk/what-we-do/planning/digital-planning/planning-london-datahub and current limitations 
- [x] Link live applications to location

Create system that enables colour to change as planning status changes as follows
- [ ] Does he community think a planning application is likely to be submitted?
- [ ] Has a planning application been submitted?  Yellow (tbc)
- [ ] Is whole building demolition proposed? Add Pink outline (tbc) 
- [ ] Has the application been approved? Yes/Approved -change to Orange (tbc). No/ Rejected - change to Red 
- [ ] Has approved work begun? Yes- change to Green, No - leave orange   
- [ ] Add date (not visualised)
- [ ] Is there in appeal? Add Red outline to Green approval
- [ ] If multiple appeals- thicken outline with each appeal. 
- [ ] Is the new work completed and the building in use, Change to turquoise (tbc) (colour shows for say 6 months only) e.g. turquoise

 - [ ] Signpost limitations of live streaming for users
 How long should approved applications be visualised for?
How is historical data stored? 
@matkoniecz See Hackney for interesting planning application visualisation  
![image](https://user-images.githubusercontent.com/42236514/168865617-cab27862-dfbb-49fb-b7fe-6448da21f679.png) Link no longer works was for  London Borough of Hackney. Find My Nearest (Map). Web. Accessed March 21, 2021. https://hackney.gov.uk/find-my-nearest-map. if u can find again

**Comment by matkoniecz** [comment]
I have created https://github.com/colouring-london/planning-datahub-investigation with summary of what I obtained so far.

I also send an email to planningdata@London.gov.uk in attempt to get more info about location data (not sure is the full polygon data available somehow)

**Comment by polly64** [comment]
@matkoniecz  
Hi Mateusz
Under both COMMUNITY & PLANNING
- [ ] Add text **Click if you think a planning application is _likely_ to be submitted here**? (PINK);
- [ ] provide test samples to see what we should be colouring to maximise location accuracy e.g UPRN point data combined with OSMM polygon and INSPIRE land parcel?  and OS address data? 
- [ ] Can we also integrate an open OS address product?- this is also necessary to improve the planning application search - at the moment we can only search by postcode 
- [ ] Create 'Date of entry' box
- [ ] Create verification button
- [ ] Create pop up text saying 'Needs to refreshed after 3 months
- [ ] Under COMMUNITY only create pop-up text to say 'click PLANNING category for visualisation of live planning applications'
Also 
- [ ] Activate Colouring Britain
and later
- [ ]  Create auto colour-fade to duller tone after 3 months (2nd stage)

**Comment by matkoniecz** [comment]
@polly64 Replaced by several rounds of later implementation/review/redesigns

Though let me know if you see something here that we lost and needs to be implemented!
