### ISSUE TITLE
Stress test the full CL setup documentation and improve it

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-london#697]
- [x] Test [dev env](https://github.com/colouring-cities/colouring-london/blob/master/docs/setup-dev-environment.md) setup
    - At least some of this is automated when running `vagrant up` by [vm_provision.sh](https://github.com/colouring-cities/colouring-london/blob/master/provision/vm_provision.sh)
    - Can I just use [these steps](https://github.com/colouring-cities/colouring-london-config)?
- [ ] Test [prod env](https://github.com/colouring-cities/colouring-london/blob/master/docs/setup-production-environment.md) setup
- [x] Link to the above in README
- [x] Tidy the README's in `/etl`
- [ ] and `/migrations`
    - (perhaps integrate into a single manual on the main README)
- [ ] Move this [issue template](https://github.com/colouring-london/colouring-london/blob/master/.github/ISSUE_TEMPLATE/deploy.md) into [colouring-london-config](https://github.com/colouring-london/colouring-london-config) and refine as needed

**Comment by edwardchalstrey1** [comment]
Hi @matkoniecz - is there a live link for the CL staging server hosted site that you look at to test changes, and is it https://clstaging.casa.ucl.ac.uk/ as suggested in the issue template you linked above?

**Comment by matkoniecz** [comment]
It is https://cl-staging.uksouth.cloudapp.azure.com/ (see https://github.com/colouring-cities/colouring-london-config )

https://clstaging.casa.ucl.ac.uk seems to be not loading

**Comment by edwardchalstrey1** [comment]
Thanks @matkoniecz

**Comment by edwardchalstrey1** [comment]
Problems with install so far seem to be:

1. `sudo apt-get install -y postgresql-12-postgis-3`:
  -  `E: Unable to locate package postgresql-12-postgis-3`
2. `npm install` has an error - long, need to see logs

**Comment by edwardchalstrey1** [comment]
Thanks @tomalrussell looks like setting the postegres repository for apt worked!

I'm taking a look at the npm log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/lib/node/node-v12.18.1/bin/node',
1 verbose cli   '/usr/local/lib/node/node-v12.18.1/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'npm@next'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.1
4 verbose npm-session bc17450a659cd3e2
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/npm 307ms
8 silly fetchPackageMetaData error for npm@next No matching version found for npm@next.
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 354ms
11 verbose type tag
12 verbose stack npm: No matching version found for npm@next.
12 verbose stack     at pickManifest (/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:122:13)
12 verbose stack     at /usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:24:14
12 verbose stack     at tryCatcher (/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
12 verbose stack     at Promise._settlePromise (/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
12 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
12 verbose stack     at Promise._settlePromises (/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
12 verbose stack     at _drainQueueStep (/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
12 verbose stack     at _drainQueue (/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
12 verbose stack     at Async._drainQueues (/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
12 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
12 verbose stack     at processImmediate (internal/timers.js:456:21)
13 verbose cwd /home/vagrant
14 verbose Linux 4.15.0-163-generic
15 verbose argv "/usr/local/lib/node/node-v12.18.1/bin/node" "/usr/local/lib/node/node-v12.18.1/bin/npm" "install" "-g" "npm@next"
16 verbose node v12.18.1
17 verbose npm  v6.14.5
18 error code ETARGET
19 error notarget No matching version found for npm@next.
20 error notarget In most cases you or one of your dependencies are requesting
20 error notarget a package version that doesn't exist.
21 verbose exit [ 1, true ]
```

**Comment by tomalrussell** [comment]
That's reasonable. Node 12 LTS will leave maintenance mode this year, so switching to 16 should be on the TODO list, whether that's part of this work or to follow - https://nodejs.org/en/about/releases/

**Comment by edwardchalstrey1** [comment]
@tomalrussell @matkoniecz I wonder if you've had a similar problem in setting up npm with the vagrant vm? Basically the problem seems to be that when `npm install` is run from `/vagrant/app`, it's expecting to see this `dir` called `node_modules` which doesn't seem to exist:

`npm ERR! path /vagrant/app/node_modules/mapnik`

**Comment by edwardchalstrey1** [comment]
```
(colouringlondon) vagrant@vagrant:/vagrant/app$ npm install
npm ERR! code 1
npm ERR! path /vagrant/app/node_modules/mapnik
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@12.18.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.9 found at "/home/vagrant/colouringlondon/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v12.18.1/node-v12.18.1-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v12.18.1/node-v12.18.1-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v12.18.1/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v12.18.1/SHASUMS256.txt
npm ERR! gyp info spawn /home/vagrant/colouringlondon/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/vagrant/app/node_modules/mapnik/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/vagrant/app/node_modules/mapnik/common.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/vagrant/.cache/node-gyp/12.18.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/vagrant/.cache/node-gyp/12.18.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/vagrant/.cache/node-gyp/12.18.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/vagrant/app/node_modules/mapnik',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR! gyp ERR! System Linux 4.15.0-163-generic
npm ERR! gyp ERR! command "/usr/local/lib/node/node-v12.18.1/bin/node" "/usr/local/lib/node/node-v12.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /vagrant/app/node_modules/mapnik
npm ERR! gyp ERR! node -v v12.18.1
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2022-01-28T16_00_14_600Z-debug-0.log
```

**Comment by matkoniecz** [comment]
I am not using vagrant - I tried fixing it but failed and right now started doing other things as discussed on the last meeting.

https://github.com/matkoniecz/fresh_database_alt are my notes from my initial setup, but I have not tried to reproduce it. While `setup1.sh` `setup2.sh` should be just runnable, for `setup3.sh` I just did some of steps copying it into CLI.

Once this was done I imported database from staging server so I have never tested polygon import step (I also planned to do this).

My plans for the next step of fixing dev environment setup was 

- set up a brand new isolated 20.04 VM
- redo that steps there and check is it resulting in a working environment.
- compare Vagrant script with my script
- try to turn it my script docker setup
 
I managed to setup dev environment once but it is possible that either:

- I did steps missing from that list
- some of steps could be done outside VM, on my host machine
- I manage to break CL and make it no longer installable (unlikely)

**Comment by matkoniecz** [comment]
I would first try setup it again to check can I still achieve this

BTW, if I broke setup then the https://github.com/colouring-cities/colouring-london/pull/700 is the most likely reason. Other changes were not touching setup at all.

**Comment by edwardchalstrey1** [comment]
> I think there's a problem with webpack peer dependencies (mini-css-extract-plugin?) - could be worked around by first asking for webpack 4 in package.json, run `npm install`, then install webpack 5.

@tomalrussell this seems to be the issue I'm stuck on too, I can't get your solution to work though, are you sure that's all you did to fix the dependency circle here?

```
(colouringlondon) vagrant@vagrant:/vagrant/app$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: colouring-london-app@1.0.0
npm ERR! Found: webpack@5.68.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^5.68.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.4.0" from mini-css-extract-plugin@0.9.0
npm ERR! node_modules/mini-css-extract-plugin
npm ERR!   dev mini-css-extract-plugin@"^0.9.0" from the root project
```

**Comment by matkoniecz** [comment]
this specific error can be solved by making a supposedly safe upgrades: https://github.com/colouring-cities/colouring-london/commit/f20cb8a73d8ad3d0b460b8c314ec7b20b3ec84c4

this is not actually solving `webpack5` problem, just a different error (entire package deprecated and fundamentally incompatible with `webpack5` - not investigated it further)

**Comment by edwardchalstrey1** [comment]
Thanks, I seem to have got around this by using webpack 4.46.0 in the package.json as Tom suggested and also switching to using node version `12.22.0` (I think it was 12.8 or something before)

Now I am back to the issues with mapnik and gyp

**Comment by edwardchalstrey1** [comment]
Just making a note of things I have tried.

On a fresh Ubuntu VM, I ran the node setup steps from here, with the current master branch of colouring london checked out and again we have the issue with `mapnik` on `npm install`:

```
azureuser@cl-dev-test:~$ cd ./colouring-london/app && npm install
npm ERR! code 1
npm ERR! path /home/azureuser/colouring-london/app/node_modules/mapnik
```

and it doesn't seem to install any of the node modules

**Comment by tomalrussell** [comment]
I had a look at running through this the other evening, have just pushed the package.json and package-lock.json state that I ended up with on [`feature/node16`](https://github.com/colouring-cities/colouring-london/tree/feature/node16), running with node v16 (current LTS). This seems to install cleanly if I delete node_modules and rerun `npm i`.

Have you started on a Dockerfile anywhere @edwardchalstrey1 ? I can take a look at working against that if it would be most helpful.

**Comment by edwardchalstrey1** [comment]
I've been fiddling with Vagrant so far since we already made a start on that and to just try and figure out the node dependencies - looks like the changes on your branch are working when I run `npm install` with node 16 on an Ubuntu VM - thx!

Now I just need to do something about this memory allocation to make the Vagrant version work I think, getting this on `npm install`:

```
 default: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

On Docker, I found a useful [blog post](https://medium.com/nsoft/building-and-running-nodejs-typescript-postgresql-application-with-docker-3878240a2f73) that may be helpful for Dockerising the application - will look at this next.

**Comment by matkoniecz** [comment]
>  default: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

https://github.com/colouring-cities/colouring-london/blob/463711317d2b97215af608456fbae76cd643b8a7/Vagrantfile#L36 ?

**Comment by edwardchalstrey1** [comment]
> > default: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
> 
> https://github.com/colouring-cities/colouring-london/blob/463711317d2b97215af608456fbae76cd643b8a7/Vagrantfile#L36
> 
> ?

Ah thanks, this branch didn't have that commit, will try now

**Comment by tomalrussell** [comment]
> On Docker, I found a useful blog post that may be helpful for Dockerising the application - will look at this next.

Great. This looks broadly sensible - you might/might not want to bother with the pgAdmin setup. I like the general outline of a docker compose for db + app, and mounted volumes for source code and data. 

Choice of base image - might be easiest to build off the official ubuntu 20.04 image, as we've most experience there. Otherwise the official node image is built on debian, might be easy enough to adapt. Alpine (as used in the blogpost) is likely to be difficult with its own package manager and musl libc.

**Comment by matkoniecz** [comment]
I would go with Ubuntu 20.04 to match staging/production. Unless it is impossible or has atrocious performance for some reason.

**Comment by edwardchalstrey1** [comment]
Closing as superseded by other issues
