### ISSUE TITLE
Facilitate building attribute data upload for Team

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-london#730]
@matkoniecz @edwardchalstrey1 CLHEAG committee priority to activate

- [x] Add main Note to contributor in a blue box (using same format as for 'Current use') saying:
'Can you help us capture information on who built the current building?'

- [x] 1a. Add text 'Do you wish to add information on:
'The main building?' OR 'A major extension?'

This answer leads you to the same questions for each option:
- [x] 2a. Add question 'When was the work carried out?' 
(If this relates to the main building and not an extension, and the age already been provided under 'Age ', it should automatically prepopulate - as code for age in Dynamics, but also make sure if someone adds age for Team that it prepopulates the other way too i.e. in Age)
- [x] 2b. Add verify- to also verify at same time for same entry in  'Age'
- [ ] ~~2c. Add Source link but no verification for source (only allow urls to be entered)~~

- [x] 3a. Add question: 'What type of developer built the building?'  
(This is the dropdown for ownership as under 'Community' which i have just noticed  hasn't been activated- i thought it had could you check?)
a) State
b) Charity
c) Community/Cooperative
d) Other non-profit body
f)  Private (jndividual)
g) Private (company/estate)
h) Other

- [x] 4.a Add 'Who was/were the main designer/s?' (Free text. First name,  space, then Last name- include constraints to maximise security i.e. max number of characters) Use plus button as in land use to allow addition of up to five designers
- [x] 4b. Add verify
- [x] 4c. Add Source link but no verification for source
- [x] 4d. How best describes the lead designer?
Landowner
Speculative builder
Government architecture department
Architectural firm
Engineering firm
Other

- [x]  5.a Add 'Did the team win any awards for this building?' 

- [x] 5b. If yes 'Add source link' and plus button so you can add up to 5

**Comment by polly64** [comment]
@matkoniecz @edwardchalstrey1 CLHEAG committee priority to activate

- [ ] Add main Note to contributor in a blue box (using same format as for 'Current use') saying:
'Can you help us capture information on who built the current building?'

- [ ] Then offer option"
'Do you wish to add information on:
the main building? OR a major extension?

This takes you to the following questions:

- [ ] 'When was the work carried out (provide option for Year as in 'Age') - if this relates to the main building this should also autofill to/from the 'Age' section (as Maciek has set up for Age/Dynamics)

- [ ] 'Who was the Developer? (Free text First name /Last name)

- [ ] 'Who was the landower?
(use same dropdown as for ownership under 'Community' and  also implement Community/Team category autofil for one if other if filled in)  NB no link asked to source here for privacy
- [ ] Developer name (free text First name /Last name)

- [ ] Who was the main designer?
Select from dropdown as below:
Landowner
Speculative builder/developer
Volume house builder
Government architect dept
Architectural firm
Engineer
Other
- [ ] Designer name/s? (free text)
First name /Last name- allow for multiple name to be added using plus sign (as in Dynamics for new development details)
- [ ] Please add links to further information on building teams here (url)


- [ ]  Has the team won any prizes/awards? (Yes/No)
- [ ]  Please add links here (url)
- [(this will eventually link to the sustainability section)

**Comment by matkoniecz** [comment]
@polly64 

>  'Do you wish to add information on: the main building? OR a major extension?

Is it supposed to be yes/no field?

Or is it supposed to be possible to answer all this questions for both (1) initial construction (2) major extension (3) another major extension (4) yet another extension etc?

In case of the second version it would be much harder to implement properly.

**Comment by tomalrussell** [comment]
Just to chip in on names - see these [notes on personal names](https://www.w3.org/International/questions/qa-personal-names) which walks through some of the variety in personal names.

Suggest a single "name" or "full name" field for simplicity, with generous character limit (perhaps 90).

**Comment by polly64** [comment]
@tomalrussell  thanks @matkoniecz

**Comment by polly64** [comment]
@edwardchalstrey1 have updated teams list

**Comment by edwardchalstrey1** [comment]
> 2c. Add Source link but no verification for source (only allow urls to be entered)
@polly64 few Qs:

1. Should this part work the same way as for the Age category, with both a "Source of information" dropdown and a "Text and Image Links" text box?
2. For the case where 'The main building' is selected, should we again inherit the values for both of those from the Age category? When 'A major extension' is selected, we can have them empty, the same as for the 'When was the work carried out?' dropdown.
3. Why do we not want Verify button(s) here? Since these have been added for the Source and Source link fields elsewhere

**Comment by polly64** [comment]
Hi @edwardchalstrey1 looking great. I've just been testing and this is list to come out of it

GENERAL

Stop digits moving so you actually have to type in number as v easy to accidentally alter and we don't really need this option

    Add copy tool for each entry on all sections and also user ability to 'Copy All' at top

LOCATION

    Activate all the boxes that are restricted but use the same protection as for name i.e. if address or building name maximum number of characters and need for gap between road name and word road/street/avenue etc

FOR TEAM

Remove 'NO' option on awards
Change to text to read 'Who was/were the developer/s'
Change developer dropdown to read ' Commercial company' (rather than Private company) and Change ' State' to read 'Government department or body'
Change Engineer to ' Engineer/Engineering firm'
With the extension we should add rename extension to be 'Major extension, restoration retrofit or refurbishment'
When you click on this section it should then give option to tick any of these 4 options separately or all. Once ticked it should give the option to fill in all subcategories as we have them for the main building
The blue and orange ticks and crosses are a bit complicated, can we just have the blue save button and clear options for each - I also noticed i couldn't go backwards on the developer drop down once I had made a choice

    Create new category at top 'Landowner at time of construction' which allows for a name/names to be added
    and also add source box

FOR AGE

Add a source link under 'facade'
Link up the major extension/retrofit etc section in team so it is reproduced here and whenever one is filled, it fills the other

    Add a 'Built from x to x ' option (see if you can copy from dynamics) below the first box

FOR PLANNING

Under Listed buildings add a 'NHLE list entry link' box for urls
Activate greyed out boxes
Change 'Is listed' to 'Is it listed'
