### ISSUE TITLE
Docs: Data structure and relationship between TOID / UPRN / Building

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-london#76]
Take some examples to show what we mean by `building` where this is;

> Yes, we took each OS building feature directly as a "building", so building_id <-> toid is 1 to 1
> Commonsense buildings could span multiple features, or multiple buildings could be represented by a single building

Take a couple of map extracts for examples using British museum (one id many toids) UCL one id many actual buildings

**Comment by polly64** [comment]
Hi @matkoniecz could you check whether this can be closed?

**Comment by matkoniecz** [comment]
I guess that additional info, if needed would go to https://github.com/colouring-cities/manual/wiki/G2.-BUILDING-FOOTPRINTS-SOURCES#colouring-britain ?

Is enough stated there?
