### ISSUE TITLE
Deployment scripts and instructions not working (deprecated?)

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [colouring-cities/colouring-london#766]
**Describe the problem**
Our team has tried installing Colouring-London locally on our servers to assess the ease of deployment and customisation (for a new geographical area) and possibly recommend adoption to our partners. We have tried vagrant up and the provision script and other instructions but the installation process fails at various stages.  

**To Reproduce**

We tried vagrant up but it fails from the start.

We also tried to the vm_provision script in a Ubuntu 20.04 docker container but first npm packages would fail to install then some python scripts (python get_test_polygons.py) failed with imports.

**Expected behavior**

Local VM ready to be provisioned & configured, web and backend services running properly.

**Comments**

I can provide more details about what we tried and what fails exactly. But a more general question for us is whether the instructions and provisioning scripts are still up to date and supposed to work with the latest version of the repository?

If not we'd be interested to learn if and when you are planning to update them.

Thanks in advance for your help !

**Comment by tomalrussell** [comment]
Hi @geoffroy-noel-ddh - thanks for the issue, @edwardchalstrey1 is currently working on bringing the setup and deployment up to date, see the discussion at https://github.com/colouring-cities/colouring-london/discussions/765 - we'd appreciate your input on approaches and are definitely keen to make this a lot easier!

See also recent background in #764 and a bit of work looking at vagrant and ubuntu 20.04 on #762

**Comment by geoffroy-noel-ddh** [comment]
Thanks for the prompt reply and the pointers. I realise now that my question was well timed as I was probably working on trying to port the provision script to docker & 20.04 as you were having conversations about similar tasks!

Unfortunately we can't contribute much as we are at the feasibility stage and looking at different options so there's no resource on our side for anything more than for quickly testing initial deployment & customisation instructions. 

We are familiar with Vagrant but we've migrated our projects to Docker because we find it lighter, faster to spin up and better for composition & re-euse. One common requirement for us and our research partners, particularly individual researchers with limited access to funding and technical assistance, is the ability to run instances locally first or on our servers preferably with no dependencies to cloud services.

**Comment by edwardchalstrey1** [comment]
Thanks for your input @geoffroy-noel-ddh - sounds like our thoughts on this are broadly aligned - as Tom suggests, stay tuned because I'm hoping that a month from now we should have some clearer documentation and likely docker setup.

I also hope to implement an automated deployment script with Terraform that could help with your server setup (depending on your timeline). see #764 & #765

**Comment by edwardchalstrey1** [comment]
Also see #697 as once I've fixed this up that will hopefully help in advance of any automation with docker

**Comment by edwardchalstrey1** [comment]
@geoffroy-noel-ddh there is an updated version of the documentation for setting up a dev environment on #776 which you may find helpful. I still need to test loading the map data.

**Comment by matkoniecz** [comment]
https://github.com/colouring-cities/colouring-london/blob/master/docs/setup-dev-environment.md should be now working for Ubuntu 18.04

**Comment by edwardchalstrey1** [comment]
^ @geoffroy-noel-ddh
