### ISSUE TITLE
Set map boundary in intelligent way

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-london#804]
Update `etl/drop_outside_limit.sh`, test it and add to documentation. Perhaps add an argument that specifies whether the boundary is London or Britain.

**Comment by tomalrussell** [comment]
There's a GeoJSON file containing the GLA boundary in `/app/public/geometries`

That script expects a shapefile, so you may need to add a `ogr2ogr` step to convert from GeoJSON to ShapeFile:
```bash
ogr2ogr -t_srs EPSG:3857 -f "ESRI Shapefile" boundary.shp boundary-detailed.geojson  # convert format and CRS
bash drop_outside_limit.sh boundary.shp
```

For Britain, there would be no need to drop geometries - we'd most likely want to include everthing covered by OS.

The script already takes the path to a file to use as the boundary as an argument. It expects that file to be a ShapeFile with a single feature (Polygon or MultiPolygon should be fine). This feature will be used to filter and drop any building footprints which are not properly contained within it.
