### ISSUE TITLE
Changes to source details on Age and Current Use

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-london#821]
- [x] Remove "Source details" box for Age category
- [x] Make source link/ text and image links boxes not appear for Age/Current Use categories when either of the top 2 options are selected for "Source of information"

**Comment by edwardchalstrey1** [comment]
Hi @polly64 the minor changes described above are now live at https://cl-staging.uksouth.cloudapp.azure.com/ 

Could you check it works as expected?

I'll look at #811 next

**Comment by polly64** [comment]
Hi @edwardchalstrey1 looks great,
