### ISSUE TITLE
Fix verify counter

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-london#855]
Problem:
The verification counter does not increment when multiple users verify the same field, it gets stuck on 1 or 0.

**Comment by edwardchalstrey1** [comment]
@tomalrussell @matkoniecz I took a look at this today but it's unclear to me how we currently get the verification number from the database - is it possible this was never implemented?

Trying to trace through the codebase where/how we can load the count from the `building_verification` table:

1. https://github.com/colouring-cities/colouring-london/blob/master/app/src/frontend/building/data-components/verification.tsx <- here at line 45 is where the `verified_count` gets displayed, so I'm trying to understand where the value `props.verified_count` comes from
2. https://github.com/colouring-cities/colouring-london/blob/master/app/src/frontend/building/data-containers/age.tsx <- for each of the categories, the fields with verification buttons (all of them now) have a `verified_count` parameter e.g. `verified_count={props.building.verified.date_year}`
3. ... so I trace this back to https://github.com/colouring-cities/colouring-london/blob/master/app/src/frontend/building/data-containers/category-view-props.ts and then https://github.com/colouring-cities/colouring-london/blob/master/app/src/frontend/models/building.ts where we have this variable `BuildingAttributeVerificationCounts` being set up - but from here I'm unsure how the code gets the count number?

What do you think is the right approach here? Do I need to do something like add a new query called `verified_count` to https://github.com/colouring-cities/colouring-london/blob/master/app/src/tiles/dataDefinition.ts and then import this function where the count gets added to `props`?

**Comment by tomalrussell** [comment]
See #878 which has a change (should be a fix for this) to the code which counts up verifications - they get tacked on to the building object and returned via an API call.
