### ISSUE TITLE
Latest data extract is more than 2 months old

### ISSUE THREAD

**Issue by aelmekeev** [colouring-cities/colouring-london#870]
**Describe the problem**
[Latest data extract](https://colouring.london/data-extracts.html) is from Mon Apr 25 2022

**To Reproduce**
1. Go to https://colouring.london/data-extracts.html

**Expected behavior**
Latest data extract from 1 July / end of June

**More information**
I'm not 100% sure if it's an issue with this codebase. I've actually failed to find the job itself though the script to extract the data seems to be located here hence I've decided to report it here instead of https://discuss.colouring.london/ which does not look active.

Off topic: thank you for the great project! I would like to use data as a way to find new items for my collection. Will repay back with some data contributions if successful! :)

**Comment by polly64** [comment]
thanks for your comment, engineering team will get back, and for your positive comments on project. We would welcome any open data contributions.

**Comment by matkoniecz** [comment]
Regular extracts will be now working again.

I triggered one manually right now and it is listed at https://colouring.london/data-extracts.html .

Thanks for reporting this!
