### ISSUE TITLE
Planning visualisation tool questions

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-london#884]
# Questions

- [x] Section Title (under Planning category): _Planning Application Status_
- [x] Add Disclaimer - to be agreed 

**In  Green box** **(automated)**
- [x] Add title for box  _'Local Authority planning information'_ and add items below 
- [x] Add _'Data Source'_: The Planning London DataHub Greater London Authority plus hyperlink 
- [x] Add _'Planning Application ID'_
- [x] Add '_Most recent update by data provider_'
- [x] Add _'Planning Portal link'_ from url_planning_app field - if not available should say 'link not provided'
- [x] Add '_Current planning application status for this site_':
- [x] Add either _'Submitted', 'Approved', 'Rejected', 'Withdrawn', 'Appealed'_
- [x] Add _'Date'_
- [x] Add _'Brief Description of proposed work'_ (max 400 characters) plus _'Show more...'_
- [ ] Add Development constraints (see issues below)
- [ ] Add Conservation area layer on map (Ian Hall dataset) 
    - option to switch on/off

**Out of Green box (crowdsourced)**
- [ ] Add _'Do you think a planning application _is going to_ be submitted for this site that is not currently visualised?'_ 
- [ ] Add _'Edit date'_ - link this to edit history/automated
(crowdsourced)
- [ ] Add _'Are you aware of a planning application that has been _recently_ submitted for this site and is not listed below?'_ 
- [ ] Add _'Edit date'_ - link this to edit history/automated
- [ ] Add _'Has the work on this site been completed?'_ (crowdsourced)
- [ ] Add  _'Estimated date of completion'_ (crowdsourced- link this to age section to autopopulate 'latest possible construction date)

**Issues/Comments**
- Protections/permissions needed e.g. Listed buildings consent / conservation area consent (should be able to see on map if required / empty box), etc. Also areas of archaeological priority, SSSI, local listed buildings (Ian Hall developing dataset) - to be discussed

- Question on demolition 'Do you expect this building to be demolished?'
Preferable to show demolition question both in "Community" and "Planning" section
- Multiple planning applications can apply to a single building, including multiple active applications and visualise latest
- Colours for specific planning stages can be changed

**Comment by fallipalaiologou** [comment]
@polly64 we currently call the section 'Planning Status' see [here](https://colouringlondon.org/view/planning/2478530). Should we leave as is or rename to 'Planning Application updates' ?

**Comment by polly64** [comment]
@fallipalaiologou  I think probably a compromise is good i.e. Planning Application Status.

**Comment by polly64** [comment]
@fallipalaiologou   I have also added a section which says is there a planning application submitted for this site above

**Comment by fallipalaiologou** [comment]
> @fallipalaiologou We also really need a question which says is there a planning application submitted for this site which isn;t Yes/No - as we might not have access to data on all applications - so just has a 'yes box that can be left unticked what do you think?

@polly64 yes, we can do that but then it would be good if we could visualise these entries with a different colour to distinguish from official data? (or find another way to distinguish them)

**Comment by matkoniecz** [comment]
@polly64 

>  Add 'Data Source': The Planning London DataHub Greater London Authority plus hyperlink

https://www.london.gov.uk/what-we-do/planning/digital-planning/planning-london-datahub - right?

**Comment by polly64** [comment]
@matkoniecz actually would use this link as takes them straight to data 
https://data.london.gov.uk/dataset/planning-london-datahub?_gl=1%2aprwpc%2a_ga%2aMzQyOTg0MjcxLjE2NTk0NDA4NTM.

**Comment by fallipalaiologou** [comment]
@matkoniecz @polly64 In case a polygon does show any data (i.e. it is not coloured), then what info to put in Green Box? Perhaps as follows:

- [ ] Show Section title: 'Planning Application Status'
- [ ] Show 'Disclaimer: data is imported from the official source, but Planning London DataHub is known to be incomplete."
- [ ] Show message: "No live planning data available currently for this building polygon via the Planning London DataHub ."

**Comment by fallipalaiologou** [comment]
@matkoniecz for conservation area layer, please edit the text to show citation: 

- [ ] Show conservation area boundaries from '[English Conservation Area dataset 2020](http://www.bedfordpark.net/leo/planning/)' by Ian Hall.

**Comment by polly64** [comment]
@fallipalaiologou @matkoniecz 
hi think this one should be change to 

Show 'Disclaimer: Planning application status is visualised using data uploaded by local authorities to the Greater London Authority's Planning London DataHub (add link). Please note that these data are currently incomplete and also often do not provide information on minor alterations. For comprehensive information on all applications please visit the UK Planning Portal site. "

@fallipalaiologou have we heard back re considerate contractors' data? do drop me an email

**Comment by matkoniecz** [comment]
>(add link)

Should it be also https://data.london.gov.uk/dataset/planning-london-datahub?_gl=1%2aprwpc%2a_ga%2aMzQyOTg0MjcxLjE2NTk0NDA4NTM ?

**Comment by polly64** [comment]
yes that's good

**Comment by matkoniecz** [comment]
processed/superseded
