### ISSUE TITLE
Include autogenerated specific entry listings in Planning

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-london#933]
@polly64 

Can you try to track down links to specific entry listings for 

 - [x] "Is the building on the [National Heritage List for England](https://historicengland.org.uk/advice/hpg/heritage-assets/nhle/)?" - https://historicengland.org.uk/listing/the-list/list-entry/1080446?section=official-list-entry
 - [ ] "Is it on the [Heritage at Risk](https://historicengland.org.uk/advice/heritage-at-risk/search-register/) register?"
 - [ ] "Is it a [Locally Listed Heritage Asset](https://historicengland.org.uk/advice/hpg/has/locallylistedhas/)?"
 - [ ] "Is it within a [World Heritage Site](https://historicengland.org.uk/advice/hpg/has/whs/)?"
 - [ ] "Is it recorded on the [Historic Environment Record](https://historicengland.org.uk/advice/technical-advice/information-management/hers/)?"
 - [ ] "Is it in an [Archaeological Priority Area](https://historicengland.org.uk/services-skills/our-planning-services/greater-london-archaeology-advisory-service/greater-london-archaeological-priority-areas/)?"
 - [ ] "Does it have an [Historic Area Assessment](https://historicengland.org.uk/images-books/publications/understanding-place-historic-area-assessments/)?"

?

**Comment by matkoniecz** [comment]
What is the id format: pure numbers or is say 106a also a potential id?

**Comment by matkoniecz** [comment]
@polly64 

https://cl-staging.uksouth.cloudapp.azure.com/edit/planning/2956004 - can you simply give example of links that user would put as answer, in currently deployed staging version. That would answer my need for "links to specific entry listings"

**Comment by matkoniecz** [comment]
@polly64 

Can you write text for "How to find iD" minitutorials?

**Comment by matkoniecz** [comment]
Ideally this boxes here would narrow, with link on the right side. Not promising this version, will try to implement

![Untitled](https://user-images.githubusercontent.com/899988/191785103-a13b56ae-a058-4903-9360-2bcbecd11953.png)

**Comment by matkoniecz** [comment]
@polly64 

It looks like this:

![screen27](https://user-images.githubusercontent.com/899988/191978647-4ec11ff7-64b9-4c85-b34f-d462bde21556.png)

**Comment by polly64** [comment]
@matkoniecz round corners better if we use them elsewhere. Can we get the 2 boxes next to each other? with ID to left and hyperlink to word 'ID Link' to right  Can you also send me the github issue link for the ID's i need to check? - can't seem to find it

**Comment by matkoniecz** [comment]
I will put note about round corners in #937 (apparently general text and numeric fields do not have them...)

@polly64 see https://github.com/colouring-cities/colouring-london/issues/933#issue-1382467697 (in this issue)

![screen29](https://user-images.githubusercontent.com/899988/191985376-82353baf-e864-42c2-8022-fcfe828b78ae.png)

**Comment by matkoniecz** [comment]
was done by #946
