### ISSUE TITLE
Some forms do not have rounded corners - is it deliberate?

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-london#937]
@polly64 

Or should it be changed so all forms have round corners?

![screen28](https://user-images.githubusercontent.com/899988/191978869-45c0c69d-0721-4be7-8591-ff611f1ea3d3.png)

**Comment by matkoniecz** [comment]
per https://github.com/colouring-cities/colouring-london/issues/933#issuecomment-1256269206 we should have round corners also here

**Comment by matkoniecz** [comment]
@polly64 What about login form? Should it be also changed?

![screen32](https://user-images.githubusercontent.com/899988/192095926-505ed3c5-ec0d-40f4-ba6c-b072495c5cf5.png)
![screen31](https://user-images.githubusercontent.com/899988/192095929-9ab6ff8c-49b0-4a5a-a1ab-60bc71a40648.png)

**Comment by polly64** [comment]
@matkoniecz no its not deliberate, fine to make all the same
