### ISSUE TITLE
IDs for planing

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#938]
**Describe the solution**

**Describe any alternatives**

**Additional context**
Other context or background information.

**Comment by matkoniecz** [comment]
https://cl-staging.uksouth.cloudapp.azure.com/edit/planning/2956004 - can you simply give example of links that user would put as answer, in currently deployed staging version?

for "Is the building on the [National Heritage List for England](https://historicengland.org.uk/advice/hpg/heritage-assets/nhle/)?" it could be https://historicengland.org.uk/listing/the-list/list-entry/1080446?section=official-list-entry

 - [ ] "Is it on the [Heritage at Risk](https://historicengland.org.uk/advice/heritage-at-risk/search-register/) register?"
 - [ ] "Is it a [Locally Listed Heritage Asset](https://historicengland.org.uk/advice/hpg/has/locallylistedhas/)?"
 - [ ] "Is it within a [World Heritage Site](https://historicengland.org.uk/advice/hpg/has/whs/)?"
 - [ ] "Is it recorded on the [Historic Environment Record](https://historicengland.org.uk/advice/technical-advice/information-management/hers/)?"
 - [ ] "Is it in an [Archaeological Priority Area](https://historicengland.org.uk/services-skills/our-planning-services/greater-london-archaeology-advisory-service/greater-london-archaeological-priority-areas/)?"
 - [ ] "Does it have an [Historic Area Assessment](https://historicengland.org.uk/images-books/publications/understanding-place-historic-area-assessments/)?"
What is the id format: pure numbers or is say 106a also a potential id for any of them?

**Comment by polly64** [comment]
@matkoniecz have just written to HE with queries and will add whatever links I can now but some are problematic

**Comment by polly64** [comment]
@matkoniecz  still saying database error  when i add NHLE link.

**Comment by matkoniecz** [comment]
> will add whatever links I can now 

Great!

> but some are problematic

In which way? There is no id? There is no possibility to provide link at all

>  when i add NHLE link.

should work now

**Comment by polly64** [comment]
@matkoniecz comemnts above

**Comment by polly64** [comment]
@matkoniecz - I.m actually not sure we are going to be able to get IDs or links for heritage assessment or the Historic environment record - I can't seem to find any but we can wait for HE response
- you can only get PDF links for APAs  and for conservation area (appraisals) but no central database like NHLE
- For heritage at risk appears to be no database just a website you scroll through with NHLE ID numbers
- World heritage sites fine can get from UNSESCO page link 
- Locally listed buildings - Ian hall is in process of creating national register. [For moment 
-  you have to go to each borough and find register as PDF for all buildings i.e (https://www.islington.gov.uk/~/media/sharepoint-lists/public-records/planningandbuildingcontrol/information/adviceandinformation/20192020/20190925registeroflocallylistedbuildingsandshopfrontsapril2010.pdf)

**Comment by polly64** [comment]
@matkoniecz so I think we are going to have to pause on some of this while we wait for HE. But we should still prioristise  

[ ]  reorder as issue 939

- [ ]do the ID links just for Listed buildings and WHS. 

- [ ] For APAs and locally listed buildings we  just need to be able to add PDF links for the moment. 

- [ ] For CAs there is an ID and there are PDF appraisal docs for each conservation area which will contain multiple buildings.

- [ ]  For HAA and HERs just leave blank as these are v complicated.

**Comment by matkoniecz** [comment]
@polly64 

> reorder as https://github.com/colouring-cities/colouring-london/issues/939

Done, I think (please look at staging or https://github.com/colouring-cities/colouring-london/issues/939#issuecomment-1256641868 is it what you expected - or is more that reorder needed)

>  do the ID links just for Listed buildings and WHS.

So for WHS link like https://whc.unesco.org/en/list/488 is expected, right? (you can see how it works on staging)

>  For APAs and locally listed buildings we just need to be able to add PDF links for the moment.

So no change needed, from the current amorphous link input?

> For CAs there is an ID and there are PDF appraisal docs for each conservation area which will contain multiple buildings.

So introduce id field and keep link input? Or do not make changes and keep as is right now with link input?

**Comment by polly64** [comment]
> @matkoniecz 
> 
> > reorder as #939
> 
> Done, I think (please look at staging or [#939 (comment)](https://github.com/colouring-cities/colouring-london/issues/939#issuecomment-1256641868) is it what you expected - or is more that reorder needed)

yes thanks
> 
> > do the ID links just for Listed buildings and WHS.

yes for the  moment
> 
> So for WHS link like https://whc.unesco.org/en/list/488 is expected, right? (you can see how it works on staging)

yes this looks v good
> 
> > For APAs and locally listed buildings we just need to be able to add PDF links for the moment.
> 
> So no change needed, from the current amorphous link input?

I think we should be explicit as to what they have to do and say in each box 'Please add relevant link here'
> 
> > For CAs there is an ID and there are PDF appraisal docs for each conservation area which will contain multiple buildings.
> 
> So introduce id field and keep link input? Or do not make changes and keep as is right now with link input?

So yes have ID field but we can't connect this to a set link so we have to have a link box which has ' Please add CA appraisal link here' written in it 

Also please add (CA) after 'conservation area' in question if you think  isn't obvious what CA refers to

PS I personal think the please is probably  important as if you say 'Add this here' compared to 'please add this here' the second implies that you are requesting engagement for which you are grateful and the first sounds both a bit bossy but also like just like an impersonal  instruction of what to do how. What do you think?

**Comment by matkoniecz** [comment]
> I think we should be explicit as to what they have to do and say in each box 'Please add relevant link here'

Changing `https://...` to `Please add relevant link here` then

> PS I personal think the please is probably important as if you say 'Add this here' compared to 'please add this here' the second implies that you are requesting engagement for which you are grateful and the first sounds both a bit bossy but also like just like an impersonal instruction of what to do how. What do you think?

I agree, and if there is enough space to fit it, then it is better to include also "please"

> So yes have ID field but we can't connect this to a set link so we have to have a link box which has ' Please add CA appraisal link here' written in it

> Also please add (CA) after 'conservation area' in question if you think isn't obvious what CA refers to

So this one remains as the remaining segment, with everything else done.

**Comment by polly64** [comment]
@matkoniecz  ok great- let me know when you want me to check things on staging. I also have a meeting with Mike at 12 noon if we want to look at/discuss any pull requests. I can also answer any questions til then

**Comment by matkoniecz** [comment]
@polly64 Is this data display fine?

![screen09](https://user-images.githubusercontent.com/899988/193052008-55174714-596a-4ace-870d-62d5fb6190e3.png)

**Comment by matkoniecz** [comment]
@polly64 Should CA in the first hint text be expanded to the full "Conservation Area" name?

**Comment by polly64** [comment]
@matkoniecz looks good but think maybe clearer if we use 'ID' rather than 'identifier. Can u also see if there's a way of linking to the  'like me' may on , community rather Tha the expected application map

**Comment by matkoniecz** [comment]
was done by #946
