### ISSUE TITLE
change order of 'other' designation items

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#939]
Hi @matkoniecz could u, so more in line with key reorder items in 'other' designation section so order reads
1. World Heritage Site
2. Archaeological Priority Area
3. Locally listed building
4. Historic Environment Record
5. Heritage Area Assessment
thanks

**Comment by matkoniecz** [comment]
@polly64 
I reordered them, while keeping current entries and names:

![screen30](https://user-images.githubusercontent.com/899988/192051472-fe91f064-34ec-46bf-b9bc-ad64c92eb83a.png)


is it expected? Or should I also rename them and add this one extra entry?

**Comment by polly64** [comment]
@matkoniecz sorry not clear on question. We just need to reorder the above so in order on first comment
so the following order

    World Heritage Site now first and then
    Archaeological Priority Area
    Locally listed building
    Historic Environment Record
    Heritage Area Assessment

**Comment by matkoniecz** [comment]
@polly64 Oh, I misunderstood and changed things in legend.

Can you look at staging is it displaying what you wanted?

**Comment by polly64** [comment]
@matkoniecz yes great

**Comment by matkoniecz** [comment]
OK, then lest merge it into #925
