### ISSUE TITLE
Planning category- add disclaimer to designation map

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#940]
**Describe the solution**

**Describe any alternatives**

**Additional context**
Other context or background information.

**Comment by matkoniecz** [comment]
What should be the text of the disclaimer?

**Comment by polly64** [comment]
@matkoniecz   Falli and Taimaz may have other suggestions but for moment let's make it say 
'Designation data is currently incomplete. We are aiming for 100% coverage by April 2023.'

**Comment by matkoniecz** [comment]
@polly64 

Is it referring to Designation/protection layer?

Should it be added to the current

> All data relating to designated buildings should be checked on the National Heritage List for England or local authority websites where used for planning or development purposes

or replace it?

**Comment by polly64** [comment]
@matkoniecz  I think  let's a) keep the current disclaimer in the key and b) for moment also put '_Designation data is currently incomplete. We are aiming for 100% coverage by April 2023_.' as a blue box at the end of the designation section and we can discuss tomorrow

**Comment by matkoniecz** [comment]
done as part of #946 - please, open a new issue if text needs to be tweaked
