### ISSUE TITLE
add box asking for crowdsourced checking of accuracy of location for planning data

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#980]
@matkoniecz  have lost notebook what did we say text for this would be?

**Comment by matkoniecz** [comment]
> Click here if there is some issue with positioning of listing?

**Comment by matkoniecz** [comment]
That is more complex:

- we may want to record what is actually confusing/unclear/wrong
  - but freeform crowsdsourced info open all kind of problems 
- it should be recorder per application, not per building

**Comment by matkoniecz** [comment]
So we will leave it for later...

**Comment by polly64** [comment]
yes all these should be inactive thanks

**Comment by matkoniecz** [comment]
added as part of #898, for now intentionally disabled
