### ISSUE TITLE
world heritage site entry amend

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#982]
On world heritage site entry unclear where user should enter in info ie in left or right box. Add something to direct

**Comment by matkoniecz** [comment]
@polly64 Only one of them is editable, user is simply unable to edit the right one.

But maybe it should be also grayed out? Or with a gray background? Like other noneditable fields

**Comment by polly64** [comment]
Or just say add here just feels a bit unclear

**Comment by matkoniecz** [comment]
current:
![screen06](https://user-images.githubusercontent.com/899988/203407047-64f2f6ae-b860-4b21-938c-d25f2bff70b5.png)

new (?):
![screen07](https://user-images.githubusercontent.com/899988/203407057-a8a21cb6-b504-4c82-b3f6-471de9751f21.png)

**Comment by matkoniecz** [comment]
done in #985
