### ISSUE TITLE
set planning editing panel to default of all being concertinered except planning status

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#984]
set planning editing to default of all being concertinered except planning status - green boxes should be visible

**Comment by matkoniecz** [comment]
@polly64 So on the first interaction user should see something like this? With all groups except the current planning permissing being collapsed?

![screen04](https://user-images.githubusercontent.com/899988/203382266-249d3225-ba0c-4a56-9526-022fdb5d3dc0.png)

**Comment by polly64** [comment]
Yes perfect
